# Mais sobre `SELECT`

- temporary tables
- views
- variables
- subqueries

In [3]:
import mysql.connector
from functools import partial


def get_connection_helper():

    def run_db_query(connection, query, args=None):
        with connection.cursor() as cursor:
            print('Executando query:')
            cursor.execute(query, args)
            for result in cursor:
                print(result)

    connection = mysql.connector.connect(
        host='localhost',
        user='megadados',
        password='megadados',
        database='sakila',
    )
    return connection, partial(run_db_query, connection)


connection, db = get_connection_helper()

## Aquecimento

Quanta receita foi gerada para cada categoria de filmes? Liste do maior para o menor.

In [4]:
db('''
SELECT
    name, SUM(rental_rate) as receita
FROM
    rental
    INNER JOIN inventory USING (inventory_id)
    INNER JOIN film USING (film_id)
    INNER JOIN film_category USING (film_id)
    INNER JOIN category USING (category_id)
WHERE
    return_date IS NOT NULL
GROUP BY
    category_id
ORDER BY 
    receita DESC
''')

Executando query:
('Sports', Decimal('3574.36'))
('Drama', Decimal('3344.47'))
('Sci-Fi', Decimal('3264.07'))
('Animation', Decimal('3155.55'))
('Comedy', Decimal('3064.68'))
('Foreign', Decimal('3023.78'))
('Games', Decimal('2989.45'))
('Action', Decimal('2924.05'))
('Family', Decimal('2916.17'))
('New', Decimal('2873.73'))
('Travel', Decimal('2742.73'))
('Documentary', Decimal('2734.57'))
('Horror', Decimal('2591.66'))
('Children', Decimal('2525.61'))
('Music', Decimal('2512.81'))
('Classics', Decimal('2458.70'))

Liste os filmes e o numero de vezes em que foram alugados

In [5]:
db('''
SELECT
    title, COUNT(rental_id) as rentals
FROM
    film
    LEFT OUTER JOIN inventory USING (film_id)
    LEFT OUTER JOIN rental USING (inventory_id)
GROUP BY
    film_id
ORDER BY
    rentals
''')

Executando query:
('ALICE FANTASIA', 0)
('APOLLO TEEN', 0)
('ARGONAUTS TOWN', 0)
('ARK RIDGEMONT', 0)
('ARSENIC INDEPENDENCE', 0)
('BOONDOCK BALLROOM', 0)
('BUTCH PANTHER', 0)
('CATCH AMISTAD', 0)
('CHINATOWN GLADIATOR', 0)
('CHOCOLATE DUCK', 0)
('COMMANDMENTS EXPRESS', 0)
('CROSSING DIVORCE', 0)
('CROWDS TELEMARK', 0)
('CRYSTAL BREAKING', 0)
('DAZED PUNK', 0)
('DELIVERANCE MULHOLLAND', 0)
('FIREHOUSE VIETNAM', 0)
('FLOATS GARDEN', 0)
('FRANKENSTEIN STRANGER', 0)
('GLADIATOR WESTWARD', 0)
('GUMP DATE', 0)
('HATE HANDICAP', 0)
('HOCUS FRIDA', 0)
('KENTUCKIAN GIANT', 0)
('KILL BROTHERHOOD', 0)
('MUPPET MILE', 0)
('ORDER BETRAYED', 0)
('PEARL DESTINY', 0)
('PERDITION FARGO', 0)
('PSYCHO SHRUNK', 0)
('RAIDERS ANTITRUST', 0)
('RAINBOW SHOCK', 0)
('ROOF CHAMPION', 0)
('SISTER FREDDY', 0)
('SKY MIRACLE', 0)
('SUICIDES SILENCE', 0)
('TADPOLE PARK', 0)
('TREASURE COMMAND', 0)
('VILLAIN DESPERATE', 0)
('VOLUME HOUSE', 0)
('WAKE JAWS', 0)
('WALLS ARTIST', 0)
('HARDLY ROBBERS', 4)
('MIXED DOORS', 4)
('TRAIN BUNCH', 4)
('BRAVEHEART HUMAN', 5)
('BUNCH MINDS', 5)
('CONSPIRACY SPIRIT', 5)
('FEVER EMPIRE', 5)
('FREEDOM CLEOPATRA', 5)
('FULL FLATLINERS', 5)
('GLORY TRACY', 5)
('HUNTER ALTER', 5)
('INFORMER DOUBLE', 5)
('MANNEQUIN WORST', 5)
('MUSSOLINI SPOILERS', 5)
('PRIVATE DROP', 5)
('SEVEN SWARM', 5)
('TRAFFIC HOBBIT', 5)
('APOCALYPSE FLAMINGOS', 6)
('BED HIGHBALL', 6)
('BUBBLE GROSSE', 6)
('CASSIDY WYOMING', 6)
('COMANCHEROS ENEMY', 6)
('DESPERATE TRAINSPOTTING', 6)
('DUCK RACER', 6)
('DUMBO LUST', 6)
('EXTRAORDINARY CONQUERER', 6)
('FRONTIER CABIN', 6)
('GRACELAND DYNAMITE', 6)
('HAPPINESS UNITED', 6)
('HAUNTED ANTITRUST', 6)
('ITALIAN AFRICAN', 6)
('JAPANESE RUN', 6)
('JERSEY SASSY', 6)
('KILLER INNOCENT', 6)
('LADYBUGS ARMAGEDDON', 6)
('OKLAHOMA JUMANJI', 6)
('PHANTOM GLORY', 6)
('RUSHMORE MERMAID', 6)
('SCHOOL JACKET', 6)
('SIMON NORTH', 6)
('SLING LUKE', 6)
('TEQUILA PAST', 6)
('TERMINATOR CLUB', 6)
('TEXAS WATCH', 6)
('WARLOCK WEREWOLF', 6)
('WATERSHIP FRONTIER', 6)
('WILD APOLLO', 6)
('YOUTH KICK', 6)
('ACE GOLDFINGER', 7)
('BANG KWAI', 7)
('BULWORTH COMMANDMENTS', 7)
('CLERKS ANGELS', 7)
('CLUE GRAIL', 7)
('CONNECTION MICROCOSMOS', 7)
('CONTROL ANTHEM', 7)
('COWBOY DOOM', 7)
('CRUELTY UNFORGIVEN', 7)
('DIVORCE SHINING', 7)
('DOCTOR GRAIL', 7)
('DOZEN LION', 7)
('DUFFEL APOCALYPSE', 7)
('EARLY HOME', 7)
('ELF MURDER', 7)
('EVE RESURRECTION', 7)
('FIRE WOLVES', 7)
('HAWK CHILL', 7)
('HEAVENLY GUN', 7)
('ISHTAR ROCKETEER', 7)
('LEATHERNECKS DWARFS', 7)
('LESSON CLEOPATRA', 7)
('LICENSE WEEKEND', 7)
('LUKE MUMMY', 7)
('MAGIC MALLRATS', 7)
('MENAGERIE RUSHMORE', 7)
('MULHOLLAND BEAST', 7)
('NEWSIES STORY', 7)
('PANIC CLUB', 7)
('PIZZA JUMANJI', 7)
('PRESIDENT BANG', 7)
('SENSE GREEK', 7)
('SQUAD FISH', 7)
('STALLION SUNDANCE', 7)
('TREATMENT JEKYLL', 7)
('VANISHED GARDEN', 7)
('VISION TORQUE', 7)
('YOUNG LANGUAGE', 7)
('BABY HALL', 8)
('BALLROOM MOCKINGBIRD', 8)
('CASPER DRAGONFLY', 8)
('CHAPLIN LICENSE', 8)
('CHITTY LOCK', 8)
('CLYDE THEORY', 8)
('CRUSADE HONEY', 8)
('DESIRE ALIEN', 8)
('DESTINATION JERK', 8)
('GODFATHER DIARY', 8)
('GOSFORD DONNIE', 8)
('GROSSE WONDERFUL', 8)
('HAROLD FRENCH', 8)
('HOOSIERS BIRDCAGE', 8)
('JUMANJI BLADE', 8)
('LIGHTS DEER', 8)
('MAGNIFICENT CHITTY', 8)
('MAUDE MOD', 8)
('PAPI NECKLACE', 8)
('PARK CITIZEN', 8)
('PET HAUNTING', 8)
('PUNK DIVORCE', 8)
('REBEL AIRPORT', 8)
('RECORDS ZORRO', 8)
('RUNAWAY TENENBAUMS', 8)
('RUNNER MADIGAN', 8)
('SAINTS BRIDE', 8)
('SHINING ROSES', 8)
('SOLDIERS EVOLUTION', 8)
('SOUP WISDOM', 8)
('SUNSET RACER', 8)
('TARZAN VIDEOTAPE', 8)
('UNFAITHFUL KILL', 8)
('UNTOUCHABLES SUNRISE', 8)
('VERTIGO NORTHWEST', 8)
('WORLD LEATHERNECKS', 8)
('ALI FOREVER', 9)
('ANYTHING SAVANNAH', 9)
('BIRDCAGE CASPER', 9)
('CARIBBEAN LIBERTY', 9)
('CASUALTIES ENCINO', 9)
('CRAZY HOME', 9)
('DARES PLUTO', 9)
('DARLING BREAKING', 9)
('DAUGHTER MADIGAN', 9)
('DIARY PANIC', 9)
('DOLLS RAGE', 9)
('DROP WATERFRONT', 9)
('DWARFS ALTER', 9)
('FRISCO FORREST', 9)
('GHOSTBUSTERS ELF', 9)
('GILBERT PELICAN', 9)
('GUYS FALCON', 9)
('HOLY TADPOLE', 9)
('HOTEL HAPPINESS', 9)
('IMPACT ALADDIN', 9)
('INTOLERABLE INTENTIONS', 9)
('JUNGLE CLOSER', 9)
('KING EVOLUTION', 9)
('KRAMER CHOCOLATE', 9)
('LEGALLY SECRETARY', 9)
('LEGEND JEDI', 9)
('MAGUIRE APACHE', 9)
('MATRIX SNOWMAN', 9)
('MIRACLE VIRTUAL', 9)
('MONSOON CAUSE', 9)
('MONTEZUMA COMMAND', 9)
('NUTS TIES', 9)
('PLATOON INSTINCT', 9)
('RANDOM GO', 9)
('REDS POCUS', 9)
('SNATCHERS MONTEZUMA', 9)
('SPARTACUS CHEAPER', 9)
('SPEED SUIT', 9)
('VANILLA DAY', 9)
('VICTORY ACADEMY', 9)
('WISDOM WORKER', 9)
('WON DARES', 9)
('WONDERFUL DROP', 9)
('ZHIVAGO CORE', 9)
('AMELIE HELLFIGHTERS', 10)
('ANTITRUST TOMATOES', 10)
('BENEATH RUSH', 10)
('BLOOD ARGONAUTS', 10)
('CLOCKWORK PARADISE', 10)
('DOUBTFIRE LABYRINTH', 10)
('ELEMENT FREDDY', 10)
('ELIZABETH SHANE', 10)
('FIDDLER LOST', 10)
('FROGMEN BREAKING', 10)
('GONE TROUBLE', 10)
('GRAIL FRANKENSTEIN', 10)
('HALLOWEEN NUTS', 10)
('HOLLOW JEOPARDY', 10)
('JAWBREAKER BROOKLYN', 10)
('JEOPARDY ENCINO', 10)
('LAMBS CINCINATTI', 10)
('LIFE TWISTED', 10)
('LOLITA WORLD', 10)
('LOVER TRUMAN', 10)
('LUCK OPUS', 10)
('MADIGAN DORADO', 10)
('MAKER GABLES', 10)
('MYSTIC TRUMAN', 10)
('NOTTING SPEAKEASY', 10)
('OLEANDER CLUE', 10)
('PATHS CONTROL', 10)
('RESERVOIR ADAPTATION', 10)
('RIGHT CRANES', 10)
('ROLLERCOASTER BRINGING', 10)
('RUN PACIFIC', 10)
('SENSIBILITY REAR', 10)
('SMILE EARRING', 10)
('SPOILERS HELLFIGHTERS', 10)
('STAGE WORLD', 10)
('SUPERFLY TRIP', 10)
('WAGON JAWS', 10)
('WARS PLUTO', 10)
('AUTUMN CROW', 11)
('BEAST HUNCHBACK', 11)
('BEETHOVEN EXORCIST', 11)
('BIRCH ANTITRUST', 11)
('BIRD INDEPENDENCE', 11)
('BOWFINGER GABLES', 11)
('BUGSY SONG', 11)
('CRANES RESERVOIR', 11)
('DARKO DORADO', 11)
('DRAGON SQUAD', 11)
('DRUMLINE CYCLONE', 11)
('ENDING CROWDS', 11)
('FEATHERS METAL', 11)
('FRIDA SLIPPER', 11)
('FUGITIVE MAGUIRE', 11)
('GATHERING CALENDAR', 11)
('IRON MOON', 11)
('LANGUAGE COWBOY', 11)
('LORD ARIZONA', 11)
('MAGNOLIA FORRESTER', 11)
('MOD SECRETARY', 11)
('NORTH TEQUILA', 11)
('OCTOBER SUBMARINE', 11)
('OPUS ICE', 11)
('POTLUCK MIXED', 11)
('PRIX UNDEFEATED', 11)
('REEF SALUTE', 11)
('RIDER CADDYSHACK', 11)
('SANTA PARIS', 11)
('SONG HEDWIG', 11)
('SPIRITED CASUALTIES', 11)
('STONE FIRE', 11)
('STRANGER STRANGERS', 11)
('THEORY MERMAID', 11)
('THIN SAGEBRUSH', 11)
('TIES HUNGER', 11)
('TOWERS HURRICANE', 11)
('TRAINSPOTTING STRANGERS', 11)
('TWISTED PIRATES', 11)
('ADAPTATION HOLES', 12)
('AFRICAN EGG', 12)
('ALABAMA DEVIL', 12)
('BLANKET BEVERLY', 12)
('BORN SPINAL', 12)
('BRANNIGAN SUNRISE', 12)
('CALIFORNIA BIRDS', 12)
('CROW GREASE', 12)
('DANGEROUS UPTOWN', 12)
('EVOLUTION ALTER', 12)
('FINDING ANACONDA', 12)
('FLIGHT LIES', 12)
('GUNFIGHTER MUSSOLINI', 12)
('HEDWIG ALTER', 12)
('LIBERTY MAGNIFICENT', 12)
('LOST BIRD', 12)
('LOVERBOY ATTACKS', 12)
('MASSAGE IMAGE', 12)
('MEET CHOCOLATE', 12)
('MIGHTY LUCK', 12)
('MINORITY KISS', 12)
('MOB DUFFEL', 12)
('PITTSBURGH HUNCHBACK', 12)
('SAVANNAH TOWN', 12)
('SIDE ARK', 12)
('SILVERADO GOLDFINGER', 12)
('SMOOCHY CONTROL', 12)
('SORORITY QUEEN', 12)
('SPEAKEASY DATE', 12)
('TEMPLE ATTRACTION', 12)
('TYCOON GATHERING', 12)
('UPTOWN YOUNG', 12)
('VALENTINE VANISHING', 12)
('VAMPIRE WHALE', 12)
('WAR NOTTING', 12)
('WINDOW SIDE', 12)
('ANONYMOUS HUMAN', 13)
('ARABIA DOGMA', 13)
('BEDAZZLED MARRIED', 13)
('BEHAVIOR RUNAWAY', 13)
('BILKO ANONYMOUS', 13)
('BREAKING HOME', 13)
('BRIGHT ENCOUNTERS', 13)
('CHAMBER ITALIAN', 13)
('CHAMPION FLATLINERS', 13)
('CHISUM BEHAVIOR', 13)
('CINCINATTI WHISPERER', 13)
('CITIZEN SHREK', 13)
('CONNECTICUT TRAMP', 13)
('DADDY PITTSBURGH', 13)
('DARKNESS WAR', 13)
('DATE SPEED', 13)
('DRUMS DYNAMITE', 13)
('EVERYONE CRAFT', 13)
('EXORCIST STING', 13)
('EXPRESS LONELY', 13)
('FLASH WARS', 13)
('FOREVER CANDIDATE', 13)
('HOLLYWOOD ANONYMOUS', 13)
('HOOK CHARIOTS', 13)
('HUNGER ROOF', 13)
('IDENTITY LOVER', 13)
('JINGLE SAGEBRUSH', 13)
('LAWRENCE LOVE', 13)
('LUCKY FLYING', 13)
('MEMENTO ZOOLANDER', 13)
('MICROCOSMOS PARADISE', 13)
('MILE MULAN', 13)
('MONTEREY LABYRINTH', 13)
('MOONWALKER FOOL', 13)
('MULAN MOON', 13)
('NATURAL STOCK', 13)
('OPPOSITE NECKLACE', 13)
('PARTY KNOCK', 13)
('PAST SUICIDES', 13)
('PURPLE MOVIE', 13)
('RAGING AIRPLANE', 13)
('ROBBERY BRIGHT', 13)
('SASSY PACKER', 13)
('SATURN NAME', 13)
('SPIKING ELEMENT', 13)
('SPINAL ROCKY', 13)
('STATE WASTELAND', 13)
('SUPER WYOMING', 13)
('TENENBAUMS COMMAND', 13)
('TUXEDO MILE', 13)
('USUAL UNTOUCHABLES', 13)
('WYOMING STORM', 13)
('ALLEY EVOLUTION', 14)
('ANALYZE HOOSIERS', 14)
('BLINDNESS GUN', 14)
('CONFESSIONS MAGUIRE', 14)
('CREEPERS KANE', 14)
('DANCES NONE', 14)
('DAY UNFAITHFUL', 14)
('DEEP CRUSADE', 14)
('DONNIE ALLEY', 14)
('ELEPHANT TROJAN', 14)
('GAMES BOWFINGER', 14)
('GLASS DYING', 14)
('GOLD RIVER', 14)
('GREEDY ROOTS', 14)
('GRINCH MASSAGE', 14)
('HAMLET WISDOM', 14)
('HOME PITY', 14)
('IMAGE PRINCESS', 14)
('IMPOSSIBLE PREJUDICE', 14)
('JAWS HARRY', 14)
('KANE EXORCIST', 14)
('LOVELY JINGLE', 14)
('MADRE GABLES', 14)
('MOTHER OLEANDER', 14)
('NEMO CAMPUS', 14)
('NOTORIOUS REUNION', 14)
('OUTLAW HANKY', 14)
('PAJAMA JAWBREAKER', 14)
('PARIS WEEKEND', 14)
('PEACH INNOCENT', 14)
('PERSONAL LADYBUGS', 14)
('SADDLE ANTITRUST', 14)
('SEARCHERS WAIT', 14)
('SHANE DARKNESS', 14)
('SHANGHAI TYCOON', 14)
('SHRUNK DIVINE', 14)
('SPLASH GUMP', 14)
('STAMPEDE DISTURBING', 14)
('STOCK GLASS', 14)
('TOMATOES HELLFIGHTERS', 14)
('TOWN ARK', 14)
('TROOPERS METAL', 14)
('TURN STAR', 14)
('UNCUT SUICIDES', 14)
('VIRTUAL SPOILERS', 14)
('WEREWOLF LOLA', 14)
('WRATH MILE', 14)
('AIRPLANE SIERRA', 15)
('ANTHEM LUKE', 15)
('BETRAYED REAR', 15)
('BOILED DARES', 15)
('CABIN FLASH', 15)
('CHARADE DUFFEL', 15)
('CIRCUS YOUTH', 15)
('CYCLONE FAMILY', 15)
('DEVIL DESIRE', 15)
('DIRTY ACE', 15)
('DIVINE RESURRECTION', 15)
('EDGE KISSING', 15)
('ENTRAPMENT SATISFACTION', 15)
('HOLES BRANNIGAN', 15)
('HOLIDAY GAMES', 15)
('HUMAN GRAFFITI', 15)
('HUNTING MUSKETEERS', 15)
('HYSTERICAL GRAIL', 15)
('ILLUSION AMELIE', 15)
('LABYRINTH LEAGUE', 15)
('LONELY ELEPHANT', 15)
('LOSER HUSTLER', 15)
('LUST LOCK', 15)
('MADISON TRAP', 15)
('MANCHURIAN CURTAIN', 15)
('MODEL FISH', 15)
('MODERN DORADO', 15)
('MONSTER SPARTACUS', 15)
('MOSQUITO ARMAGEDDON', 15)
('NASH CHOCOLAT', 15)
('NECKLACE OUTBREAK', 15)
('ODDS BOOGIE', 15)
('PANKY SUBMARINE', 15)
('PANTHER REDS', 15)
('RINGS HEARTBREAKERS', 15)
('SCISSORHANDS SLUMS', 15)
('SHIP WONDERLAND', 15)
('SHREK LICENSE', 15)
('SIEGE MADRE', 15)
('SIERRA DIVIDE', 15)
('SONS INTERVIEW', 15)
('SPIRIT FLINTSTONES', 15)
('STEERS ARMAGEDDON', 15)
('SUBMARINE BED', 15)
('SWEET BROTHERHOOD', 15)
('TOOTSIE PILOT', 15)
('TRANSLATION SUMMER', 15)
('VALLEY PACKER', 15)
('VIETNAM SMOOCHY', 15)
('WASTELAND DIVINE', 15)
('WORKER TARZAN', 15)
('ARMY FLINTSTONES', 16)
('ARTIST COLDBLOODED', 16)
('ATTACKS HATE', 16)
('BAKED CLEOPATRA', 16)
('BONNIE HOLOCAUST', 16)
('BULL SHAWSHANK', 16)
('CADDYSHACK JEDI', 16)
('CASABLANCA SUPER', 16)
('CHICAGO NORTH', 16)
('COLDBLOODED DARLING', 16)
('COMMAND DARLING', 16)
('CONQUERER NUTS', 16)
('CRAFT OUTFIELD', 16)
('CREATURES SHAKESPEARE', 16)
('DAISY MENAGERIE', 16)
('DESTINY SATURDAY', 16)
('DUDE BLINDNESS', 16)
('GASLIGHT CRUSADE', 16)
('GRADUATE LORD', 16)
('HALL CASSIDY', 16)
('HOMEWARD CIDER', 16)
('INDIAN LOVE', 16)
('JEEPERS WEDDING', 16)
('LOCK REAR', 16)
('MERMAID INSECTS', 16)
('MOTIONS DETAILS', 16)
('MOULIN WAKE', 16)
('MUMMY CREATURES', 16)
('PATRIOT ROMAN', 16)
('PAYCHECK WAIT', 16)
('PICKUP DRIVING', 16)
('PILOT HOOSIERS', 16)
('PLUTO OLEANDER', 16)
('PRIDE ALAMO', 16)
('PURE RUNNER', 16)
('QUILLS BULL', 16)
('REAP UNFAITHFUL', 16)
('ROCKY WAR', 16)
('RULES HUMAN', 16)
('SAGEBRUSH CLUELESS', 16)
('SILENCE KANE', 16)
('SLIPPER FIDELITY', 16)
('STREAK RIDGEMONT', 16)
('SUMMER SCARFACE', 16)
('TRAP GUYS', 16)
('UPRISING UPTOWN', 16)
('VARSITY TRIP', 16)
('WANDA CHAMBER', 16)
('WATCH TRACY', 16)
('WEST LION', 16)
('WILLOW TRACY', 16)
('WIZARD COLDBLOODED', 16)
('WORDS HUNTER', 16)
('WORST BANGER', 16)
('BEACH HEARTBREAKERS', 17)
('BIKINI BORROWERS', 17)
('BREAKFAST GOLDFINGER', 17)
('COMFORTS RUSH', 17)
('CONFUSED CANDLES', 17)
('CONVERSATION DOWNHILL', 17)
('DYING MAKER', 17)
('EGYPT TENENBAUMS', 17)
('FACTORY DRAGON', 17)
('FERRIS MOTHER', 17)
('FLINTSTONES HAPPINESS', 17)
('FREAKY POCUS', 17)
('FRENCH HOLIDAY', 17)
('GANDHI KWAI', 17)
('GREEK EVERYONE', 17)
('HANOVER GALAXY', 17)
('HOLOCAUST HIGHBALL', 17)
('IDAHO LOVE', 17)
('INTENTIONS EMPIRE', 17)
('JEKYLL FROGMEN', 17)
('JERICHO MULAN', 17)
('JOON NORTHWEST', 17)
('LADY STAGE', 17)
('LAWLESS VISION', 17)
('LEAGUE HELLFIGHTERS', 17)
('LOUISIANA HARRY', 17)
('MAJESTIC FLOATS', 17)
('MASK PEACH', 17)
('MIDNIGHT WESTWARD', 17)
('MUSKETEERS WAIT', 17)
('NEWTON LABYRINTH', 17)
('NOON PAPI', 17)
('ORIENT CLOSER', 17)
('PERFECT GROOVE', 17)
('POSEIDON FOREVER', 17)
('POTTER CONNECTICUT', 17)
('REAR TRADING', 17)
('ROCK INSTINCT', 17)
('ROOTS REMEMBER', 17)
('SATISFACTION CONFIDENTIAL', 17)
('SLACKER LIAISONS', 17)
('STRANGERS GRAFFITI', 17)
('SUGAR WONKA', 17)
('TAXI KICK', 17)
('TEEN APOLLO', 17)
('UNITED PILOT', 17)
('VIRGIN DAISY', 17)
('WATERFRONT DELIVERANCE', 17)
('ZOOLANDER FICTION', 17)
('AIRPORT POLLOCK', 18)
('ALONE TRIP', 18)
('BAREFOOT MANCHURIAN', 18)
('BIRDS PERDITION', 18)
('BOULEVARD MOB', 18)
('CANDIDATE PERDITION', 18)
('CAROL TEXAS', 18)
('CLEOPATRA DEVIL', 18)
('CORE SUIT', 18)
('DARN FORRESTER', 18)
('DAWN POND', 18)
('DRAGONFLY STRANGERS', 18)
('DRIVER ANNIE', 18)
('ENOUGH RAGING', 18)
('EXPECATIONS NATURAL', 18)
('FORREST SONS', 18)
('GALAXY SWEETHEARTS', 18)
('GROOVE FICTION', 18)
('GROUNDHOG UNCUT', 18)
('HEAVEN FREEDOM', 18)
('HOPE TOOTSIE', 18)
('INCH JET', 18)
('INSECTS STONE', 18)
('INSTINCT AIRPORT', 18)
('JACKET FRISCO', 18)
('JADE BUNCH', 18)
('LION UNCUT', 18)
('MISSION ZOOLANDER', 18)
('PARADISE SABRINA', 18)
('POLISH BROOKLYN', 18)
('POLLOCK DELIVERANCE', 18)
('RACER EGG', 18)
('REMEMBER DIARY', 18)
('ROUGE SQUAD', 18)
('SCARFACE BANG', 18)
('SECRETARY ROUGE', 18)
('SMOKING BARBARELLA', 18)
('SWEDEN SHINING', 18)
('UNFORGIVEN ZOOLANDER', 18)
('VANISHING ROCKY', 18)
('WEEKEND PERSONAL', 18)
('WHALE BIKINI', 18)
('WONKA SEA', 18)
('BACKLASH UNDEFEATED', 19)
('BILL OTHERS', 19)
('BRIDE INTRIGUE', 19)
('CAMPUS REMEMBER', 19)
('CANYON STOCK', 19)
('CIDER DESIRE', 19)
('CLONES PINOCCHIO', 19)
('CLUB GRAFFITI', 19)
('DESERT POSEIDON', 19)
('DETAILS PACKER', 19)
('DISCIPLE MOTHER', 19)
('DOORS PRESIDENT', 19)
('EARRING INSTINCT', 19)
('ENCINO ELF', 19)
('ENCOUNTERS CURTAIN', 19)
('EYES DRIVING', 19)
('FANTASIA PARK', 19)
('FICTION CHRISTMAS', 19)
('FURY MURDER', 19)
('GABLES METROPOLIS', 19)
('GORGEOUS BINGO', 19)
('HANGING DEEP', 19)
('HONEY TIES', 19)
('HOURS RAGE', 19)
('IGBY MAKER', 19)
('INDEPENDENCE HOTEL', 19)
('JEDI BENEATH', 19)
('MARS ROMAN', 19)
('MINE TITANS', 19)
('MUSIC BOONDOCK', 19)
('NATIONAL STORY', 19)
('NEIGHBORS CHARADE', 19)
('NOVOCAINE FLIGHT', 19)
('PATIENT SISTER', 19)
('POND SEATTLE', 19)
('RAGE GAMES', 19)
('REQUIEM TYCOON', 19)
('ROAD ROXANNE', 19)
('ROXANNE REBEL', 19)
('SHAWSHANK BUBBLE', 19)
('SOMETHING DUCK', 19)
('SUNDANCE INVASION', 19)
('THIEF PELICAN', 19)
('TROJAN TOMORROW', 19)
('VOICE PEACH', 19)
('BRINGING HYSTERICAL', 20)
('CHASING FIGHT', 20)
('CHEAPER CLYDE', 20)
('CHOCOLAT HARRY', 20)
('DALMATIONS SWEDEN', 20)
('DINOSAUR SECRETARY', 20)
('FLYING HOOK', 20)
('GARDEN ISLAND', 20)
('GO PURPLE', 20)
('HARPER DYING', 20)
('HEARTBREAKERS BRIGHT', 20)
('HELLFIGHTERS SIERRA', 20)
('HUNCHBACK IMPOSSIBLE', 20)
('INSIDER ARIZONA', 20)
('INTERVIEW LIAISONS', 20)
('INTRIGUE WORST', 20)
('JERK PAYCHECK', 20)
('JET NEIGHBORS', 20)
('KICK SAVANNAH', 20)
('KISSING DOLLS', 20)
('LOVE SUICIDES', 20)
('MASKED BUBBLE', 20)
('MILLION ACE', 20)
('MINDS TRUMAN', 20)
('MONEY HAROLD', 20)
('NORTHWEST POLISH', 20)
('OUTFIELD MASSACRE', 20)
('PEAK FOREVER', 20)
('PINOCCHIO SIMON', 20)
('PREJUDICE OLEANDER', 20)
('QUEST MUSSOLINI', 20)
('REDEMPTION COMFORTS', 20)
('REIGN GENTLEMEN', 20)
('REUNION WITCHES', 20)
('RIVER OUTLAW', 20)
('ROOM ROMAN', 20)
('SECRETS PARADISE', 20)
('SLEEPLESS MONSOON', 20)
('SPICE SORORITY', 20)
('STEPMOM DREAM', 20)
('STRAIGHT HOURS', 20)
('TRAMP OTHERS', 20)
('WRONG BEHAVIOR', 20)
('AGENT TRUMAN', 21)
('AMADEUS HOLY', 21)
('AMISTAD MIDSUMMER', 21)
('ANACONDA CONFESSIONS', 21)
('ARIZONA BANG', 21)
('ARMAGEDDON LOST', 21)
('BADMAN DAWN', 21)
('BASIC EASY', 21)
('BERETS AGENT', 21)
('BEVERLY OUTLAW', 21)
('BLUES INSTINCT', 21)
('BROOKLYN DESERT', 21)
('CALENDAR GUNFIGHT', 21)
('CAUSE DATE', 21)
('CHAINSAW UPTOWN', 21)
('CHARIOTS CONSPIRACY', 21)
('CHRISTMAS MOONSHINE', 21)
('COAST RAINBOW', 21)
('CROSSROADS CASUALTIES', 21)
('DECEIVER BETRAYED', 21)
('DIVIDE MONSTER', 21)
('DOOM DANCING', 21)
('DRACULA CRYSTAL', 21)
('DRIVING POLISH', 21)
('EGG IGBY', 21)
('EMPIRE MALKOVICH', 21)
('EXCITEMENT EVE', 21)
('FIDELITY DEVIL', 21)
('FIREBALL PHILADELPHIA', 21)
('GHOST GROUNDHOG', 21)
('GREASE YOUTH', 21)
('HIGHBALL POTTER', 21)
('LEBOWSKI SOLDIERS', 21)
('MOONSHINE CABIN', 21)
('MOURNING PURPLE', 21)
('OPEN AFRICAN', 21)
('PIANIST OUTFIELD', 21)
('PIRATES ROXANNE', 21)
('RESURRECTION SILVERADO', 21)
('SABRINA MIDNIGHT', 21)
('SECRET GROUNDHOG', 21)
('SLEEPY JAPANESE', 21)
('SLEUTH ORIENT', 21)
('SPLENDOR PATTON', 21)
('STAR OPERATION', 21)
('STING PERSONAL', 21)
('SUIT WALLS', 21)
('UNBREAKABLE KARATE', 21)
('UNDEFEATED DALMATIONS', 21)
('VACATION BOONDOCK', 21)
('WAIT CIDER', 21)
('WOLVES DESIRE', 21)
('ALIEN CENTER', 22)
('ALTER VICTORY', 22)
('AMERICAN CIRCUS', 22)
('ANGELS LIFE', 22)
('ANNIE IDENTITY', 22)
('BANGER PINOCCHIO', 22)
('BEAR GRACELAND', 22)
('BEAUTY GREASE', 22)
('BLADE POLISH', 22)
('BORROWERS BEDAZZLED', 22)
('CHICKEN HELLFIGHTERS', 22)
('CHILL LUCK', 22)
('CONGENIALITY QUEST', 22)
('DREAM PICKUP', 22)
('EAGLES PANKY', 22)
('FALCON VOLUME', 22)
('FIGHT JAWBREAKER', 22)
('FLATLINERS KILLER', 22)
('GRAPES FURY', 22)
('HAUNTING PIANIST', 22)
('HEAD STRANGER', 22)
('HIGH ENCINO', 22)
('HOMICIDE PEACH', 22)
('HUSTLER PARTY', 22)
('KISS GLORY', 22)
('LIAISONS SWEET', 22)
('MALTESE HOPE', 22)
('MIDSUMMER GROUNDHOG', 22)
('PACKER MADIGAN', 22)
('QUEEN LUKE', 22)
('SEA VIRGIN', 22)
('SHAKESPEARE SADDLE', 22)

('SINNERS ATLANTIS', 22)
('SNATCH SLIPPER', 22)
('SOUTH WAIT', 22)
('TOURIST PELICAN', 22)
('VOLCANO TEXAS', 22)
('WHISPERER GIANT', 22)
('WONDERLAND CHRISTMAS', 22)
('ACADEMY DINOSAUR', 23)
('AFFAIR PREJUDICE', 23)
('ALADDIN CALENDAR', 23)
('BALLOON HOMEWARD', 23)
('CANDLES GRAPES', 23)
('CARRIE BUNCH', 23)
('CROOKED FROGMEN', 23)
('CUPBOARD SINNERS', 23)
('EARTH VISION', 23)
('EASY GLADIATOR', 23)
('FLAMINGOS CONNECTICUT', 23)
('FOOL MOCKINGBIRD', 23)
('FREDDY STORM', 23)
('GENTLEMEN STAGE', 23)
('HEAVYWEIGHTS BEAST', 23)
('HOUSE DYNAMITE', 23)
('KARATE MOON', 23)
('KWAI HOMEWARD', 23)
('MURDER ANTITRUST', 23)
('NAME DETECTIVE', 23)
('OTHERS SOUP', 23)
('OUTBREAK DIVINE', 23)
('PATTON INTERVIEW', 23)
('PHILADELPHIA WIFE', 23)
('SALUTE APOLLO', 23)
('SCORPION APOLLO', 23)
('SNOWMAN ROLLERCOASTER', 23)
('STEEL SANTA', 23)
('STRICTLY SCARFACE', 23)
('TITANIC BOONDOCK', 23)
('TROUBLE DATE', 23)
('TRUMAN CRAZY', 23)
('WASH HEAVENLY', 23)
('WIND PHANTOM', 23)
('WOMEN DORADO', 23)
('YENTL IDAHO', 23)
('ALAMO VIDEOTAPE', 24)
('ARACHNOPHOBIA ROLLERCOASTER', 24)
('ATLANTIS CAUSE', 24)
('ATTRACTION NEWTON', 24)
('BOUND CHEAPER', 24)
('CAPER MOTIONS', 24)
('CELEBRITY HORN', 24)
('CENTER DINOSAUR', 24)
('COLOR PHILADELPHIA', 24)
('DRIFTER COMMANDMENTS', 24)
('FARGO GANDHI', 24)
('GOLDFINGER SENSIBILITY', 24)
('GUNFIGHT MOON', 24)
('HORN WORKING', 24)
('HURRICANE AFFAIR', 24)
('ICE CROSSING', 24)
('JASON TRAP', 24)
('JUMPING WRATH', 24)
('KNOCK WARLOCK', 24)
('LOLA AGENT', 24)
('MAIDEN HOME', 24)
('MOCKINGBIRD HOLLYWOOD', 24)
('ORANGE GRAPES', 24)
('OZ LIAISONS', 24)
('PACIFIC AMISTAD', 24)
('ROMAN PUNK', 24)
('SEATTLE EXPECATIONS', 24)
('SHOOTIST SUPERFLY', 24)
('SLEEPING SUSPECTS', 24)
('SLUMS DUCK', 24)
('STRANGELOVE DESIRE', 24)
('SUNRISE LEAGUE', 24)
('WEDDING APOLLO', 24)
('BARBARELLA STREETCAR', 25)
('CLASH FREDDY', 25)
('CLUELESS BUCKET', 25)
('CONEHEADS SMOOCHY', 25)
('DOUBLE WRATH', 25)
('DOWNHILL ENOUGH', 25)
('DYNAMITE TARZAN', 25)
('EFFECT GLADIATOR', 25)
('ESCAPE METROPOLIS', 25)
('FEUD FROGMEN', 25)
('FISH OPUS', 25)
('GUN BONNIE', 25)
('HILLS NEIGHBORS', 25)
('MADNESS ATTACKS', 25)
('MALLRATS UNITED', 25)
('METAL ARMAGEDDON', 25)
('NIGHTMARE CHILL', 25)
('OSCAR GOLD', 25)
('SAMURAI LION', 25)
('SHEPHERD MIDSUMMER', 25)
('SHOW LORD', 25)
('STREETCAR INTENTIONS', 25)
('SUN CONFESSIONS', 25)
('TELEMARK HEARTBREAKERS', 25)
('TOMORROW HUSTLER', 25)
('TRADING PINOCCHIO', 25)
('WORKING MICROCOSMOS', 25)
('ALASKA PHANTOM', 26)
('BROTHERHOOD BLANKET', 26)
('COMA HEAD', 26)
('CONTACT ANONYMOUS', 26)
('DISTURBING SCARFACE', 26)
('DURHAM PANKY', 26)
('FANTASY TROOPERS', 26)
('FELLOWSHIP AUTUMN', 26)
('HALF OUTFIELD', 26)
('HANKY OCTOBER', 26)
('HYDE DOCTOR', 26)
('INNOCENT USUAL', 26)
('ISLAND EXORCIST', 26)
('MALKOVICH PET', 26)
('METROPOLIS COMA', 26)
('PELICAN COMFORTS', 26)
('PITY BOUND', 26)
('POCUS PULP', 26)
('SEABISCUIT PUNK', 26)
('STAGECOACH ARMAGEDDON', 26)
('TIGHTS DAWN', 26)
('TRACY CIDER', 26)
('VELVET TERMINATOR', 26)
('WESTWARD SEABISCUIT', 26)
('BLACKOUT PRIVATE', 27)
('CAMELOT VACATION', 27)
('CHANCE RESURRECTION', 27)
('CURTAIN VIDEOTAPE', 27)
('DANCING FEVER', 27)
('DETECTIVE VISION', 27)
('DORADO NOTTING', 27)
('FORRESTER COMANCHEROS', 27)
('GANGS PRIDE', 27)
('GOLDMINE TYCOON', 27)
('HORROR REIGN', 27)
('INVASION CYCLONE', 27)
('LIES TREATMENT', 27)
('LOATHING LEGALLY', 27)
('LOSE INCH', 27)
('MOVIE SHAKESPEARE', 27)
('NONE SPIKING', 27)
('OPERATION OPERATION', 27)
('PRIMARY GLASS', 27)
('PRINCESS GIANT', 27)
('RANGE MOONWALKER', 27)
('SPY MILE', 27)
('SWARM GOLD', 27)
('TELEGRAPH VOYAGE', 27)
('TORQUE BOUND', 27)
('WARDROBE PHANTOM', 27)
('CLOSER BANG', 28)
('EXPENDABLE STALLION', 28)
('FATAL HAUNTED', 28)
('GIANT TROOPERS', 28)
('GILMORE BOILED', 28)
('HANDICAP BOONDOCK', 28)
('ROSES TREASURE', 28)
('SATURDAY LAMBS', 28)
('STORY SIDE', 28)
('TRIP NEWTON', 28)
('VOYAGE LEGALLY', 28)
('BINGO TALENTED', 29)
('BOOGIE AMELIE', 29)
('CONFIDENTIAL INTERVIEW', 29)
('DEER VIRGINIAN', 29)
('ENEMY ODDS', 29)
('FAMILY SWEET', 29)
('GLEAMING JAWBREAKER', 29)
('GREATEST NORTH', 29)
('MOON BUNCH', 29)
('STORM HAPPINESS', 29)
('SWEETHEARTS SUSPECTS', 29)
('TALENTED HOMICIDE', 29)
('TITANS JERK', 29)
('VIDEOTAPE ARSENIC', 29)
('VIRGINIAN PLUTO', 29)
('BUTTERFLY CHOCOLAT', 30)
('CAT CONEHEADS', 30)
('DOGMA FAMILY', 30)
('ENGLISH BULWORTH', 30)
('FROST HEAD', 30)
('GRAFFITI LOVE', 30)
('HARRY IDAHO', 30)
('IDOLS SNATCHERS', 30)
('MARRIED GO', 30)
('MASSACRE USUAL', 30)
('MUSCLE BRIGHT', 30)
('PULP BEVERLY', 30)
('RUGRATS SHAKESPEARE', 30)
('SHOCK CABIN', 30)
('SUSPECTS QUILLS', 30)
('WITCHES PANIC', 30)
('APACHE DIVINE', 31)
('GOODFELLAS SALUTE', 31)
('HOBBIT ALIEN', 31)
('NETWORK PEAK', 31)
('ROBBERS JOON', 31)
('RUSH GOODFELLAS', 31)
('TIMBERLAND SKY', 31)
('WIFE TURN', 31)
('ZORRO ARK', 31)
('FORWARD TEMPLE', 32)
('GRIT CLOCKWORK', 32)
('JUGGLER HARDLY', 32)
('RIDGEMONT SUBMARINE', 32)
('SCALAWAG DUCK', 32)
('ROCKETEER MOTHER', 33)
('BUCKET BROTHERHOOD', 34)

Liste os filmes e o numero de vezes em que foram alugados apenas para filmes que foram alugados mais do que a média de numero de alugueis por filme.

In [6]:
db('''
SELECT
    COUNT(rental_id) into @cnt_rental
FROM
    rental
''')

Executando query:

In [5]:
db('''
SELECT
    COUNT(film_id) into @cnt_film
FROM
    film
''')

Executando query:

In [6]:
db('''
SELECT (@cnt_rental / @cnt_film) into @avg_rental_film
''')

Executando query:

In [7]:
db('SELECT @avg_rental_film')

Executando query:
(Decimal('16.044000000'),)

In [8]:
db('''
SELECT
    title, COUNT(rental_id) as rentals
FROM
    film
    LEFT OUTER JOIN inventory USING (film_id)
    LEFT OUTER JOIN rental USING (inventory_id)
GROUP BY
    film_id
HAVING
    rentals > @avg_rental_film
''')

Executando query:
('ACADEMY DINOSAUR', 23)
('AFFAIR PREJUDICE', 23)
('AGENT TRUMAN', 21)
('AIRPORT POLLOCK', 18)
('ALADDIN CALENDAR', 23)
('ALAMO VIDEOTAPE', 24)
('ALASKA PHANTOM', 26)
('ALIEN CENTER', 22)
('ALONE TRIP', 18)
('ALTER VICTORY', 22)
('AMADEUS HOLY', 21)
('AMERICAN CIRCUS', 22)
('AMISTAD MIDSUMMER', 21)
('ANACONDA CONFESSIONS', 21)
('ANGELS LIFE', 22)
('ANNIE IDENTITY', 22)
('APACHE DIVINE', 31)
('ARACHNOPHOBIA ROLLERCOASTER', 24)
('ARIZONA BANG', 21)
('ARMAGEDDON LOST', 21)
('ATLANTIS CAUSE', 24)
('ATTRACTION NEWTON', 24)
('BACKLASH UNDEFEATED', 19)
('BADMAN DAWN', 21)
('BALLOON HOMEWARD', 23)
('BANGER PINOCCHIO', 22)
('BARBARELLA STREETCAR', 25)
('BAREFOOT MANCHURIAN', 18)
('BASIC EASY', 21)
('BEACH HEARTBREAKERS', 17)
('BEAR GRACELAND', 22)
('BEAUTY GREASE', 22)
('BERETS AGENT', 21)
('BEVERLY OUTLAW', 21)
('BIKINI BORROWERS', 17)
('BILL OTHERS', 19)
('BINGO TALENTED', 29)
('BIRDS PERDITION', 18)
('BLACKOUT PRIVATE', 27)
('BLADE POLISH', 22)
('BLUES INSTINCT', 21)
('BOOGIE AMELIE', 29)
('BORROWERS BEDAZZLED', 22)
('BOULEVARD MOB', 18)
('BOUND CHEAPER', 24)
('BREAKFAST GOLDFINGER', 17)
('BRIDE INTRIGUE', 19)
('BRINGING HYSTERICAL', 20)
('BROOKLYN DESERT', 21)
('BROTHERHOOD BLANKET', 26)
('BUCKET BROTHERHOOD', 34)
('BUTTERFLY CHOCOLAT', 30)
('CALENDAR GUNFIGHT', 21)
('CAMELOT VACATION', 27)
('CAMPUS REMEMBER', 19)
('CANDIDATE PERDITION', 18)
('CANDLES GRAPES', 23)
('CANYON STOCK', 19)
('CAPER MOTIONS', 24)
('CAROL TEXAS', 18)
('CARRIE BUNCH', 23)
('CAT CONEHEADS', 30)
('CAUSE DATE', 21)
('CELEBRITY HORN', 24)
('CENTER DINOSAUR', 24)
('CHAINSAW UPTOWN', 21)
('CHANCE RESURRECTION', 27)
('CHARIOTS CONSPIRACY', 21)
('CHASING FIGHT', 20)
('CHEAPER CLYDE', 20)
('CHICKEN HELLFIGHTERS', 22)
('CHILL LUCK', 22)
('CHOCOLAT HARRY', 20)
('CHRISTMAS MOONSHINE', 21)
('CIDER DESIRE', 19)
('CLASH FREDDY', 25)
('CLEOPATRA DEVIL', 18)
('CLONES PINOCCHIO', 19)
('CLOSER BANG', 28)
('CLUB GRAFFITI', 19)
('CLUELESS BUCKET', 25)
('COAST RAINBOW', 21)
('COLOR PHILADELPHIA', 24)
('COMA HEAD', 26)
('COMFORTS RUSH', 17)
('CONEHEADS SMOOCHY', 25)
('CONFIDENTIAL INTERVIEW', 29)
('CONFUSED CANDLES', 17)
('CONGENIALITY QUEST', 22)
('CONTACT ANONYMOUS', 26)
('CONVERSATION DOWNHILL', 17)
('CORE SUIT', 18)
('CROOKED FROGMEN', 23)
('CROSSROADS CASUALTIES', 21)
('CUPBOARD SINNERS', 23)
('CURTAIN VIDEOTAPE', 27)
('DALMATIONS SWEDEN', 20)
('DANCING FEVER', 27)
('DARN FORRESTER', 18)
('DAWN POND', 18)
('DECEIVER BETRAYED', 21)
('DEER VIRGINIAN', 29)
('DESERT POSEIDON', 19)
('DETAILS PACKER', 19)
('DETECTIVE VISION', 27)
('DINOSAUR SECRETARY', 20)
('DISCIPLE MOTHER', 19)
('DISTURBING SCARFACE', 26)
('DIVIDE MONSTER', 21)
('DOGMA FAMILY', 30)
('DOOM DANCING', 21)
('DOORS PRESIDENT', 19)
('DORADO NOTTING', 27)
('DOUBLE WRATH', 25)
('DOWNHILL ENOUGH', 25)
('DRACULA CRYSTAL', 21)
('DRAGONFLY STRANGERS', 18)
('DREAM PICKUP', 22)
('DRIFTER COMMANDMENTS', 24)
('DRIVER ANNIE', 18)
('DRIVING POLISH', 21)
('DURHAM PANKY', 26)
('DYING MAKER', 17)
('DYNAMITE TARZAN', 25)
('EAGLES PANKY', 22)
('EARRING INSTINCT', 19)
('EARTH VISION', 23)
('EASY GLADIATOR', 23)
('EFFECT GLADIATOR', 25)
('EGG IGBY', 21)
('EGYPT TENENBAUMS', 17)
('EMPIRE MALKOVICH', 21)
('ENCINO ELF', 19)
('ENCOUNTERS CURTAIN', 19)
('ENEMY ODDS', 29)
('ENGLISH BULWORTH', 30)
('ENOUGH RAGING', 18)
('ESCAPE METROPOLIS', 25)
('EXCITEMENT EVE', 21)
('EXPECATIONS NATURAL', 18)
('EXPENDABLE STALLION', 28)
('EYES DRIVING', 19)
('FACTORY DRAGON', 17)
('FALCON VOLUME', 22)
('FAMILY SWEET', 29)
('FANTASIA PARK', 19)
('FANTASY TROOPERS', 26)
('FARGO GANDHI', 24)
('FATAL HAUNTED', 28)
('FELLOWSHIP AUTUMN', 26)
('FERRIS MOTHER', 17)
('FEUD FROGMEN', 25)
('FICTION CHRISTMAS', 19)
('FIDELITY DEVIL', 21)
('FIGHT JAWBREAKER', 22)
('FIREBALL PHILADELPHIA', 21)
('FISH OPUS', 25)
('FLAMINGOS CONNECTICUT', 23)
('FLATLINERS KILLER', 22)
('FLINTSTONES HAPPINESS', 17)
('FLYING HOOK', 20)
('FOOL MOCKINGBIRD', 23)
('FORREST SONS', 18)
('FORRESTER COMANCHEROS', 27)
('FORWARD TEMPLE', 32)
('FREAKY POCUS', 17)
('FREDDY STORM', 23)
('FRENCH HOLIDAY', 17)
('FROST HEAD', 30)
('FURY MURDER', 19)
('GABLES METROPOLIS', 19)
('GALAXY SWEETHEARTS', 18)
('GANDHI KWAI', 17)
('GANGS PRIDE', 27)
('GARDEN ISLAND', 20)
('GENTLEMEN STAGE', 23)
('GHOST GROUNDHOG', 21)
('GIANT TROOPERS', 28)
('GILMORE BOILED', 28)
('GLEAMING JAWBREAKER', 29)
('GO PURPLE', 20)
('GOLDFINGER SENSIBILITY', 24)
('GOLDMINE TYCOON', 27)
('GOODFELLAS SALUTE', 31)
('GORGEOUS BINGO', 19)
('GRAFFITI LOVE', 30)
('GRAPES FURY', 22)
('GREASE YOUTH', 21)
('GREATEST NORTH', 29)
('GREEK EVERYONE', 17)
('GRIT CLOCKWORK', 32)
('GROOVE FICTION', 18)
('GROUNDHOG UNCUT', 18)
('GUN BONNIE', 25)
('GUNFIGHT MOON', 24)
('HALF OUTFIELD', 26)
('HANDICAP BOONDOCK', 28)
('HANGING DEEP', 19)
('HANKY OCTOBER', 26)
('HANOVER GALAXY', 17)
('HARPER DYING', 20)
('HARRY IDAHO', 30)
('HAUNTING PIANIST', 22)
('HEAD STRANGER', 22)
('HEARTBREAKERS BRIGHT', 20)
('HEAVEN FREEDOM', 18)
('HEAVYWEIGHTS BEAST', 23)
('HELLFIGHTERS SIERRA', 20)
('HIGH ENCINO', 22)
('HIGHBALL POTTER', 21)
('HILLS NEIGHBORS', 25)
('HOBBIT ALIEN', 31)
('HOLOCAUST HIGHBALL', 17)
('HOMICIDE PEACH', 22)
('HONEY TIES', 19)
('HOPE TOOTSIE', 18)
('HORN WORKING', 24)
('HORROR REIGN', 27)
('HOURS RAGE', 19)
('HOUSE DYNAMITE', 23)
('HUNCHBACK IMPOSSIBLE', 20)
('HURRICANE AFFAIR', 24)
('HUSTLER PARTY', 22)
('HYDE DOCTOR', 26)
('ICE CROSSING', 24)
('IDAHO LOVE', 17)
('IDOLS SNATCHERS', 30)
('IGBY MAKER', 19)
('INCH JET', 18)
('INDEPENDENCE HOTEL', 19)
('INNOCENT USUAL', 26)
('INSECTS STONE', 18)
('INSIDER ARIZONA', 20)
('INSTINCT AIRPORT', 18)
('INTENTIONS EMPIRE', 17)
('INTERVIEW LIAISONS', 20)
('INTRIGUE WORST', 20)
('INVASION CYCLONE', 27)
('ISLAND EXORCIST', 26)
('JACKET FRISCO', 18)
('JADE BUNCH', 18)
('JASON TRAP', 24)
('JEDI BENEATH', 19)
('JEKYLL FROGMEN', 17)
('JERICHO MULAN', 17)
('JERK PAYCHECK', 20)
('JET NEIGHBORS', 20)
('JOON NORTHWEST', 17)
('JUGGLER HARDLY', 32)
('JUMPING WRATH', 24)
('KARATE MOON', 23)
('KICK SAVANNAH', 20)
('KISS GLORY', 22)
('KISSING DOLLS', 20)
('KNOCK WARLOCK', 24)
('KWAI HOMEWARD', 23)
('LADY STAGE', 17)
('LAWLESS VISION', 17)
('LEAGUE HELLFIGHTERS', 17)
('LEBOWSKI SOLDIERS', 21)
('LIAISONS SWEET', 22)
('LIES TREATMENT', 27)
('LION UNCUT', 18)
('LOATHING LEGALLY', 27)
('LOLA AGENT', 24)
('LOSE INCH', 27)
('LOUISIANA HARRY', 17)
('LOVE SUICIDES', 20)
('MADNESS ATTACKS', 25)
('MAIDEN HOME', 24)
('MAJESTIC FLOATS', 17)
('MALKOVICH PET', 26)
('MALLRATS UNITED', 25)
('MALTESE HOPE', 22)
('MARRIED GO', 30)
('MARS ROMAN', 19)
('MASK PEACH', 17)
('MASKED BUBBLE', 20)
('MASSACRE USUAL', 30)
('METAL ARMAGEDDON', 25)
('METROPOLIS COMA', 26)
('MIDNIGHT WESTWARD', 17)
('MIDSUMMER GROUNDHOG', 22)
('MILLION ACE', 20)
('MINDS TRUMAN', 20)
('MINE TITANS', 19)
('MISSION ZOOLANDER', 18)
('MOCKINGBIRD HOLLYWOOD', 24)
('MONEY HAROLD', 20)
('MOON BUNCH', 29)
('MOONSHINE CABIN', 21)
('MOURNING PURPLE', 21)
('MOVIE SHAKESPEARE', 27)
('MURDER ANTITRUST', 23)
('MUSCLE BRIGHT', 30)
('MUSIC BOONDOCK', 19)
('MUSKETEERS WAIT', 17)
('NAME DETECTIVE', 23)
('NATIONAL STORY', 19)
('NEIGHBORS CHARADE', 19)
('NETWORK PEAK', 31)
('NEWTON LABYRINTH', 17)
('NIGHTMARE CHILL', 25)
('NONE SPIKING', 27)
('NOON PAPI', 17)
('NORTHWEST POLISH', 20)
('NOVOCAINE FLIGHT', 19)
('OPEN AFRICAN', 21)
('OPERATION OPERATION', 27)
('ORANGE GRAPES', 24)
('ORIENT CLOSER', 17)
('OSCAR GOLD', 25)
('OTHERS SOUP', 23)
('OUTBREAK DIVINE', 23)
('OUTFIELD MASSACRE', 20)
('OZ LIAISONS', 24)
('PACIFIC AMISTAD', 24)
('PACKER MADIGAN', 22)
('PARADISE SABRINA', 18)
('PATIENT SISTER', 19)
('PATTON INTERVIEW', 23)
('PEAK FOREVER', 20)
('PELICAN COMFORTS', 26)
('PERFECT GROOVE', 17)
('PHILADELPHIA WIFE', 23)
('PIANIST OUTFIELD', 21)
('PINOCCHIO SIMON', 20)
('PIRATES ROXANNE', 21)
('PITY BOUND', 26)
('POCUS PULP', 26)
('POLISH BROOKLYN', 18)
('POLLOCK DELIVERANCE', 18)
('POND SEATTLE', 19)
('POSEIDON FOREVER', 17)
('POTTER CONNECTICUT', 17)
('PREJUDICE OLEANDER', 20)
('PRIMARY GLASS', 27)
('PRINCESS GIANT', 27)
('PULP BEVERLY', 30)
('QUEEN LUKE', 22)
('QUEST MUSSOLINI', 20)
('RACER EGG', 18)
('RAGE GAMES', 19)
('RANGE MOONWALKER', 27)
('REAR TRADING', 17)
('REDEMPTION COMFORTS', 20)
('REIGN GENTLEMEN', 20)
('REMEMBER DIARY', 18)
('REQUIEM TYCOON', 19)
('RESURRECTION SILVERADO', 21)
('REUNION WITCHES', 20)
('RIDGEMONT SUBMARINE', 32)
('RIVER OUTLAW', 20)
('ROAD ROXANNE', 19)
('ROBBERS JOON', 31)
('ROCK INSTINCT', 17)
('ROCKETEER MOTHER', 33)
('ROMAN PUNK', 24)
('ROOM ROMAN', 20)
('ROOTS REMEMBER', 17)
('ROSES TREASURE', 28)
('ROUGE SQUAD', 18)
('ROXANNE REBEL', 19)
('RUGRATS SHAKESPEARE', 30)
('RUSH GOODFELLAS', 31)
('SABRINA MIDNIGHT', 21)
('SALUTE APOLLO', 23)
('SAMURAI LION', 25)
('SATISFACTION CONFIDENTIAL', 17)
('SATURDAY LAMBS', 28)
('SCALAWAG DUCK', 32)
('SCARFACE BANG', 18)
('SCORPION APOLLO', 23)
('SEA VIRGIN', 22)
('SEABISCUIT PUNK', 26)
('SEATTLE EXPECATIONS', 24)
('SECRET GROUNDHOG', 21)
('SECRETARY ROUGE', 18)
('SECRETS PARADISE', 20)
('SHAKESPEARE SADDLE', 22)
('SHAWSHANK BUBBLE', 19)
('SHEPHERD MIDSUMMER', 25)
('SHOCK CABIN', 30)
('SHOOTIST SUPERFLY', 24)
('SHOW LORD', 25)
('SINNERS ATLANTIS', 22)
('SLACKER LIAISONS', 17)
('SLEEPING SUSPECTS', 24)
('SLEEPLESS MONSOON', 20)
('SLEEPY JAPANESE', 21)
('SLEUTH ORIENT', 21)
('SLUMS DUCK', 24)
('SMOKING BARBARELLA', 18)
('SNATCH SLIPPER', 22)
('SNOWMAN ROLLERCOASTER', 23)
('SOMETHING DUCK', 19)
('SOUTH WAIT', 22)
('SPICE SORORITY', 20)
('SPLENDOR PATTON', 21)
('SPY MILE', 27)
('STAGECOACH ARMAGEDDON', 26)
('STAR OPERATION', 21)
('STEEL SANTA', 23)
('STEPMOM DREAM', 20)
('STING PERSONAL', 21)
('STORM HAPPINESS', 29)
('STORY SIDE', 28)
('STRAIGHT HOURS', 20)
('STRANGELOVE DESIRE', 24)
('STRANGERS GRAFFITI', 17)
('STREETCAR INTENTIONS', 25)
('STRICTLY SCARFACE', 23)
('SUGAR WONKA', 17)
('SUIT WALLS', 21)
('SUN CONFESSIONS', 25)
('SUNDANCE INVASION', 19)
('SUNRISE LEAGUE', 24)
('SUSPECTS QUILLS', 30)
('SWARM GOLD', 27)
('SWEDEN SHINING', 18)
('SWEETHEARTS SUSPECTS', 29)
('TALENTED HOMICIDE', 29)
('TAXI KICK', 17)
('TEEN APOLLO', 17)
('TELEGRAPH VOYAGE', 27)
('TELEMARK HEARTBREAKERS', 25)
('THIEF PELICAN', 19)
('TIGHTS DAWN', 26)
('TIMBERLAND SKY', 31)
('TITANIC BOONDOCK', 23)
('TITANS JERK', 29)
('TOMORROW HUSTLER', 25)
('TORQUE BOUND', 27)
('TOURIST PELICAN', 22)
('TRACY CIDER', 26)
('TRADING PINOCCHIO', 25)
('TRAMP OTHERS', 20)
('TRIP NEWTON', 28)
('TROJAN TOMORROW', 19)
('TROUBLE DATE', 23)
('TRUMAN CRAZY', 23)
('UNBREAKABLE KARATE', 21)
('UNDEFEATED DALMATIONS', 21)
('UNFORGIVEN ZOOLANDER', 18)
('UNITED PILOT', 17)
('VACATION BOONDOCK', 21)
('VANISHING ROCKY', 18)
('VELVET TERMINATOR', 26)
('VIDEOTAPE ARSENIC', 29)
('VIRGIN DAISY', 17)
('VIRGINIAN PLUTO', 29)
('VOICE PEACH', 19)
('VOLCANO TEXAS', 22)
('VOYAGE LEGALLY', 28)
('WAIT CIDER', 21)
('WARDROBE PHANTOM', 27)
('WASH HEAVENLY', 23)
('WATERFRONT DELIVERANCE', 17)
('WEDDING APOLLO', 24)
('WEEKEND PERSONAL', 18)
('WESTWARD SEABISCUIT', 26)
('WHALE BIKINI', 18)
('WHISPERER GIANT', 22)
('WIFE TURN', 31)
('WIND PHANTOM', 23)
('WITCHES PANIC', 30)
('WOLVES DESIRE', 21)
('WOMEN DORADO', 23)
('WONDERLAND CHRISTMAS', 22)
('WONKA SEA', 18)
('WORKING MICROCOSMOS', 25)
('WRONG BEHAVIOR', 20)
('YENTL IDAHO', 23)
('ZOOLANDER FICTION', 17)
('ZORRO ARK', 31)

## Views

Uma *view* é uma tabela virtual, construida a partir de um comando `SELECT`. Por exemplo: execute o código a seguir.

In [9]:
db('''
DROP VIEW IF EXISTS movie_count;
''')

db('''
CREATE VIEW movie_count AS
    SELECT 
        title, COUNT(rental_id) as cnt
    FROM
        film
        LEFT OUTER JOIN inventory USING (film_id)
        LEFT OUTER JOIN rental USING (inventory_id)
    GROUP BY
        film_id
    ORDER BY
        cnt ASC;
''')

Executando query:
Executando query:

Agora temos uma *view* chamada `movie_count`. Vamos verificar que ela funcionou, listando as 30 primeiras linhas:

In [10]:
db('''
SELECT * FROM movie_count LIMIT 30
''')

Executando query:
('ALICE FANTASIA', 0)
('APOLLO TEEN', 0)
('ARGONAUTS TOWN', 0)
('ARK RIDGEMONT', 0)
('ARSENIC INDEPENDENCE', 0)
('BOONDOCK BALLROOM', 0)
('BUTCH PANTHER', 0)
('CATCH AMISTAD', 0)
('CHINATOWN GLADIATOR', 0)
('CHOCOLATE DUCK', 0)
('COMMANDMENTS EXPRESS', 0)
('CROSSING DIVORCE', 0)
('CROWDS TELEMARK', 0)
('CRYSTAL BREAKING', 0)
('DAZED PUNK', 0)
('DELIVERANCE MULHOLLAND', 0)
('FIREHOUSE VIETNAM', 0)
('FLOATS GARDEN', 0)
('FRANKENSTEIN STRANGER', 0)
('GLADIATOR WESTWARD', 0)
('GUMP DATE', 0)
('HATE HANDICAP', 0)
('HOCUS FRIDA', 0)
('KENTUCKIAN GIANT', 0)
('KILL BROTHERHOOD', 0)
('MUPPET MILE', 0)
('ORDER BETRAYED', 0)
('PEARL DESTINY', 0)
('PERDITION FARGO', 0)
('PSYCHO SHRUNK', 0)

In [11]:
db('''
SELECT 
    * 
FROM 
    movie_count 
ORDER BY
    cnt DESC
LIMIT 30
''')

Executando query:
('BUCKET BROTHERHOOD', 34)
('ROCKETEER MOTHER', 33)
('SCALAWAG DUCK', 32)
('RIDGEMONT SUBMARINE', 32)
('JUGGLER HARDLY', 32)
('GRIT CLOCKWORK', 32)
('FORWARD TEMPLE', 32)
('ZORRO ARK', 31)
('WIFE TURN', 31)
('TIMBERLAND SKY', 31)
('RUSH GOODFELLAS', 31)
('ROBBERS JOON', 31)
('NETWORK PEAK', 31)
('HOBBIT ALIEN', 31)
('GOODFELLAS SALUTE', 31)
('APACHE DIVINE', 31)
('RUGRATS SHAKESPEARE', 30)
('BUTTERFLY CHOCOLAT', 30)
('CAT CONEHEADS', 30)
('DOGMA FAMILY', 30)
('ENGLISH BULWORTH', 30)
('FROST HEAD', 30)
('GRAFFITI LOVE', 30)
('HARRY IDAHO', 30)
('IDOLS SNATCHERS', 30)
('MASSACRE USUAL', 30)
('WITCHES PANIC', 30)
('SUSPECTS QUILLS', 30)
('SHOCK CABIN', 30)
('PULP BEVERLY', 30)

Agora suponha que alteramos a tabela `film`, mudando o nome do filme "DAZED PUNK" para "STONED PUNK".

**Atividade**: Do it.

In [12]:
db('SELECT title from film where title like "S%"')

Executando query:
('SABRINA MIDNIGHT',)
('SADDLE ANTITRUST',)
('SAGEBRUSH CLUELESS',)
('SAINTS BRIDE',)
('SALUTE APOLLO',)
('SAMURAI LION',)
('SANTA PARIS',)
('SASSY PACKER',)
('SATISFACTION CONFIDENTIAL',)
('SATURDAY LAMBS',)
('SATURN NAME',)
('SAVANNAH TOWN',)
('SCALAWAG DUCK',)
('SCARFACE BANG',)
('SCHOOL JACKET',)
('SCISSORHANDS SLUMS',)
('SCORPION APOLLO',)
('SEA VIRGIN',)
('SEABISCUIT PUNK',)
('SEARCHERS WAIT',)
('SEATTLE EXPECATIONS',)
('SECRET GROUNDHOG',)
('SECRETARY ROUGE',)
('SECRETS PARADISE',)
('SENSE GREEK',)
('SENSIBILITY REAR',)
('SEVEN SWARM',)
('SHAKESPEARE SADDLE',)
('SHANE DARKNESS',)
('SHANGHAI TYCOON',)
('SHAWSHANK BUBBLE',)
('SHEPHERD MIDSUMMER',)
('SHINING ROSES',)
('SHIP WONDERLAND',)
('SHOCK CABIN',)
('SHOOTIST SUPERFLY',)
('SHOW LORD',)
('SHREK LICENSE',)
('SHRUNK DIVINE',)
('SIDE ARK',)
('SIEGE MADRE',)
('SIERRA DIVIDE',)
('SILENCE KANE',)
('SILVERADO GOLDFINGER',)
('SIMON NORTH',)
('SINNERS ATLANTIS',)
('SISTER FREDDY',)
('SKY MIRACLE',)
('SLACKER LIAISONS',)
('SLEEPING SUSPECTS',)
('SLEEPLESS MONSOON',)
('SLEEPY JAPANESE',)
('SLEUTH ORIENT',)
('SLING LUKE',)
('SLIPPER FIDELITY',)
('SLUMS DUCK',)
('SMILE EARRING',)
('SMOKING BARBARELLA',)
('SMOOCHY CONTROL',)
('SNATCH SLIPPER',)
('SNATCHERS MONTEZUMA',)
('SNOWMAN ROLLERCOASTER',)
('SOLDIERS EVOLUTION',)
('SOMETHING DUCK',)
('SONG HEDWIG',)
('SONS INTERVIEW',)
('SORORITY QUEEN',)
('SOUP WISDOM',)
('SOUTH WAIT',)
('SPARTACUS CHEAPER',)
('SPEAKEASY DATE',)
('SPEED SUIT',)
('SPICE SORORITY',)
('SPIKING ELEMENT',)
('SPINAL ROCKY',)
('SPIRIT FLINTSTONES',)
('SPIRITED CASUALTIES',)
('SPLASH GUMP',)
('SPLENDOR PATTON',)
('SPOILERS HELLFIGHTERS',)
('SPY MILE',)
('SQUAD FISH',)
('STAGE WORLD',)
('STAGECOACH ARMAGEDDON',)
('STALLION SUNDANCE',)
('STAMPEDE DISTURBING',)
('STAR OPERATION',)
('STATE WASTELAND',)
('STEEL SANTA',)
('STEERS ARMAGEDDON',)
('STEPMOM DREAM',)
('STING PERSONAL',)
('STOCK GLASS',)
('STONE FIRE',)
('STORM HAPPINESS',)
('STORY SIDE',)
('STRAIGHT HOURS',)
('STRANGELOVE DESIRE',)
('STRANGER STRANGERS',)
('STRANGERS GRAFFITI',)
('STREAK RIDGEMONT',)
('STREETCAR INTENTIONS',)
('STRICTLY SCARFACE',)
('SUBMARINE BED',)
('SUGAR WONKA',)
('SUICIDES SILENCE',)
('SUIT WALLS',)
('SUMMER SCARFACE',)
('SUN CONFESSIONS',)
('SUNDANCE INVASION',)
('SUNRISE LEAGUE',)
('SUNSET RACER',)
('SUPER WYOMING',)
('SUPERFLY TRIP',)
('SUSPECTS QUILLS',)
('SWARM GOLD',)
('SWEDEN SHINING',)
('SWEET BROTHERHOOD',)
('SWEETHEARTS SUSPECTS',)

In [13]:
db('''
UPDATE film SET title="STONED PUNK" WHERE title="DAZED PUNK"
''')

Executando query:

Verifique agora a nossa *view*:

In [14]:
db('''
SELECT * FROM movie_count LIMIT 30
''')

Executando query:
('ALICE FANTASIA', 0)
('APOLLO TEEN', 0)
('ARGONAUTS TOWN', 0)
('ARK RIDGEMONT', 0)
('ARSENIC INDEPENDENCE', 0)
('BOONDOCK BALLROOM', 0)
('BUTCH PANTHER', 0)
('CATCH AMISTAD', 0)
('CHINATOWN GLADIATOR', 0)
('CHOCOLATE DUCK', 0)
('COMMANDMENTS EXPRESS', 0)
('CROSSING DIVORCE', 0)
('CROWDS TELEMARK', 0)
('CRYSTAL BREAKING', 0)
('STONED PUNK', 0)
('DELIVERANCE MULHOLLAND', 0)
('FIREHOUSE VIETNAM', 0)
('FLOATS GARDEN', 0)
('FRANKENSTEIN STRANGER', 0)
('GLADIATOR WESTWARD', 0)
('GUMP DATE', 0)
('HATE HANDICAP', 0)
('HOCUS FRIDA', 0)
('KENTUCKIAN GIANT', 0)
('KILL BROTHERHOOD', 0)
('MUPPET MILE', 0)
('ORDER BETRAYED', 0)
('PEARL DESTINY', 0)
('PERDITION FARGO', 0)
('PSYCHO SHRUNK', 0)

Como você pode ver, as views são tabelas virtuais que são automaticamente atualizadas quando as tabelas originais são modificadas.

In [15]:
connection.rollback()

In [16]:
db('''
SELECT * FROM movie_count LIMIT 30
''')

Executando query:
('ALICE FANTASIA', 0)
('APOLLO TEEN', 0)
('ARGONAUTS TOWN', 0)
('ARK RIDGEMONT', 0)
('ARSENIC INDEPENDENCE', 0)
('BOONDOCK BALLROOM', 0)
('BUTCH PANTHER', 0)
('CATCH AMISTAD', 0)
('CHINATOWN GLADIATOR', 0)
('CHOCOLATE DUCK', 0)
('COMMANDMENTS EXPRESS', 0)
('CROSSING DIVORCE', 0)
('CROWDS TELEMARK', 0)
('CRYSTAL BREAKING', 0)
('DAZED PUNK', 0)
('DELIVERANCE MULHOLLAND', 0)
('FIREHOUSE VIETNAM', 0)
('FLOATS GARDEN', 0)
('FRANKENSTEIN STRANGER', 0)
('GLADIATOR WESTWARD', 0)
('GUMP DATE', 0)
('HATE HANDICAP', 0)
('HOCUS FRIDA', 0)
('KENTUCKIAN GIANT', 0)
('KILL BROTHERHOOD', 0)
('MUPPET MILE', 0)
('ORDER BETRAYED', 0)
('PEARL DESTINY', 0)
('PERDITION FARGO', 0)
('PSYCHO SHRUNK', 0)

### Vamos praticar

Verifique quantas vezes o filme "COWBOY DOOM" foi alugado usando a view `movie_count`

In [17]:
db('DESCRIBE movie_count')

Executando query:
('title', b'varchar(128)', 'NO', '', None, '')
('cnt', b'bigint', 'NO', '', b'0', '')

In [18]:
db('SELECT cnt FROM movie_count WHERE title = "COWBOY DOOM"')

Executando query:
(7,)

Registre um aluguel do filme "COWBOY DOOM", feito pelo funcionario "Jon Stephens" na loja id=1 para o cliente "JESSIE BANKS", na data '2019-01-01', com data de retorno '2019-01-08'

In [19]:
db('SELECT staff_id into @staff_id FROM staff WHERE first_name = "Jon" AND last_name = "Stephens"')
db('SELECT @staff_id')

Executando query:
Executando query:
(2,)

In [20]:
db('''
SELECT
    customer_id into @customer_id
FROM
    customer
WHERE
    first_name = "JESSIE"
    AND last_name = "BANKS"
''')
db('SELECT @customer_id')

Executando query:
Executando query:
(215,)

In [21]:
db('''
SELECT
    inventory_id
FROM
    film
    INNER JOIN inventory USING (film_id)
WHERE
    title = 'COWBOY DOOM'
''')

Executando query:
(845,)
(846,)

In [22]:
db('''
SELECT
    *
FROM
    rental
WHERE
    inventory_id = 846
    AND return_date IS NULL
''')

Executando query:

In [23]:
db('DESCRIBE rental')

Executando query:
('rental_id', b'int', 'NO', 'PRI', None, 'auto_increment')
('rental_date', b'datetime', 'NO', 'MUL', None, '')
('inventory_id', b'mediumint unsigned', 'NO', 'MUL', None, '')
('customer_id', b'smallint unsigned', 'NO', 'MUL', None, '')
('return_date', b'datetime', 'YES', '', None, '')
('staff_id', b'tinyint unsigned', 'NO', 'MUL', None, '')
('last_update', b'timestamp', 'NO', '', b'CURRENT_TIMESTAMP', 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP')

In [24]:
db('''
INSERT INTO rental (
    rental_date, 
    inventory_id, 
    customer_id, 
    return_date, 
    staff_id
)
VALUES 
(
    "2019-01-01",
    845,
    @customer_id,
    "2019-01-08",
    @staff_id
)''')

Executando query:

Verifique usando a view que a contagem de alugueis do filme subiu.

In [25]:
db('SELECT cnt FROM movie_count WHERE title = "COWBOY DOOM"')

Executando query:
(8,)

Faça o *rollback* desta alteração, para não modificar a nossa querida base de dados *sakila*.

In [26]:
connection.rollback()

## Tabelas temporárias

Tabelas temporárias podem ser criadas para ajudar nas tarefas de manipulação de dados. Essas tabelas existem apenas pela duração da sessão. Para criar uma tabela temporária, basta adicionar a palavra-chave `TEMPORARY` no momento da criação.

É comum criar tabelas temporárias à partir do resultado de comandos `SELECT`. Por exemplo, a seguinte query permite montar uma tabela temporária com os filmes que duram mais que 3 horas:

In [27]:
db('''
CREATE TEMPORARY TABLE long_film 
    SELECT
        *
    FROM
        film
    WHERE
        film.length > 180;
''')

Executando query:

Podemos verificar que a tabela `long_film` agora existe:

In [28]:
db('DESCRIBE long_film')

Executando query:
('film_id', 'smallint unsigned', 'NO', '', '0', 'NULL')
('title', 'varchar(128)', 'NO', '', None, 'NULL')
('description', 'text', 'YES', '', None, 'NULL')
('release_year', 'year', 'YES', '', None, 'NULL')
('language_id', 'tinyint unsigned', 'NO', '', None, 'NULL')
('original_language_id', 'tinyint unsigned', 'YES', '', None, 'NULL')
('rental_duration', 'tinyint unsigned', 'NO', '', '3', 'NULL')
('rental_rate', 'decimal(4,2)', 'NO', '', '4.99', 'NULL')
('length', 'smallint unsigned', 'YES', '', None, 'NULL')
('replacement_cost', 'decimal(5,2)', 'NO', '', '19.99', 'NULL')
('rating', "enum('G','PG','PG-13','R','NC-17')", 'YES', '', 'G', 'NULL')
('special_features', "set('Trailers','Commentaries','Deleted Scenes','Behind the Scenes')", 'YES', '', None, 'NULL')
('last_update', 'timestamp', 'NO', '', 'CURRENT_TIMESTAMP', 'on update CURRENT_TIMESTAMP')

Muito embora ela não apareça na lista de tabelas: isso é um bug do MySQL. (https://dev.mysql.com/worklog/task/?id=648)

In [29]:
db('SHOW TABLES')

Executando query:
('actor',)
('actor_info',)
('address',)
('category',)
('city',)
('country',)
('customer',)
('customer_list',)
('film',)
('film_actor',)
('film_category',)
('film_list',)
('film_text',)
('inventory',)
('language',)
('movie_count',)
('nicer_but_slower_film_list',)
('payment',)
('rental',)
('sales_by_film_category',)
('sales_by_store',)
('staff',)
('staff_list',)
('store',)

Vamos listar o conteudo desta tabela:

In [30]:
db('SELECT title FROM long_film')

Executando query:
('ANALYZE HOOSIERS',)
('BAKED CLEOPATRA',)
('CATCH AMISTAD',)
('CHICAGO NORTH',)
('CONSPIRACY SPIRIT',)
('CONTROL ANTHEM',)
('CRYSTAL BREAKING',)
('DARN FORRESTER',)
('FRONTIER CABIN',)
('GANGS PRIDE',)
('HAUNTING PIANIST',)
('HOME PITY',)
('HOTEL HAPPINESS',)
('INTRIGUE WORST',)
('JACKET FRISCO',)
('KING EVOLUTION',)
('LAWLESS VISION',)
('LOVE SUICIDES',)
('MONSOON CAUSE',)
('MOONWALKER FOOL',)
('MUSCLE BRIGHT',)
('POND SEATTLE',)
('RECORDS ZORRO',)
('REDS POCUS',)
('RUNAWAY TENENBAUMS',)
('SATURN NAME',)
('SCALAWAG DUCK',)
('SEARCHERS WAIT',)
('SMOOCHY CONTROL',)
('SOLDIERS EVOLUTION',)
('SONS INTERVIEW',)
('SORORITY QUEEN',)
('STAR OPERATION',)
('SWEET BROTHERHOOD',)
('THEORY MERMAID',)
('WIFE TURN',)
('WILD APOLLO',)
('WORST BANGER',)
('YOUNG LANGUAGE',)

Vamos apagar a tabela `long_film`:

In [31]:
db('DROP TABLE long_film')

Executando query:

### Vamos praticar

- Crie uma tabela temporária `max_duration` que contém a duração máxima de filme para cada categoria

In [32]:
db('DROP TABLE IF EXISTS max_duration')
db('''
CREATE TEMPORARY TABLE max_duration
    SELECT
        category_id, name, MAX(length) as max_length
    FROM
        film
        INNER JOIN film_category USING (film_id)
        INNER JOIN category USING (category_id)
    GROUP BY
        category_id
''')

Executando query:
Executando query:

 - Verifique a tabela.

In [33]:
db('SELECT * FROM max_duration')

Executando query:
(1, 'Action', 185)
(2, 'Animation', 185)
(3, 'Children', 178)
(4, 'Classics', 184)
(5, 'Comedy', 185)
(6, 'Documentary', 183)
(7, 'Drama', 181)
(8, 'Family', 184)
(9, 'Foreign', 184)
(10, 'Games', 185)
(11, 'Horror', 181)
(12, 'Music', 185)
(13, 'New', 183)
(14, 'Sci-Fi', 185)
(15, 'Sports', 184)
(16, 'Travel', 185)

- Agora use a tabela temporária para construir uma tabela com as categorias e seus respectivos filmes mais longos:

In [34]:
db('''
SELECT
    length, max_length, title, name
FROM
    film
    INNER JOIN film_category USING (film_id)
    INNER JOIN max_duration USING (category_id)
WHERE
    length = max_length
''')

Executando query:
(185, 185, 'DARN FORRESTER', 'Action')
(185, 185, 'WORST BANGER', 'Action')
(185, 185, 'GANGS PRIDE', 'Animation')
(185, 185, 'POND SEATTLE', 'Animation')
(178, 178, 'FURY MURDER', 'Children')
(178, 178, 'WRONG BEHAVIOR', 'Children')
(184, 184, 'CONSPIRACY SPIRIT', 'Classics')
(185, 185, 'CONTROL ANTHEM', 'Comedy')
(183, 183, 'WIFE TURN', 'Documentary')
(183, 183, 'YOUNG LANGUAGE', 'Documentary')
(181, 181, 'JACKET FRISCO', 'Drama')
(184, 184, 'KING EVOLUTION', 'Family')
(184, 184, 'CRYSTAL BREAKING', 'Foreign')
(184, 184, 'SORORITY QUEEN', 'Foreign')
(185, 185, 'CHICAGO NORTH', 'Games')
(181, 181, 'ANALYZE HOOSIERS', 'Horror')
(181, 181, 'LOVE SUICIDES', 'Horror')
(185, 185, 'HOME PITY', 'Music')
(183, 183, 'FRONTIER CABIN', 'New')
(185, 185, 'SOLDIERS EVOLUTION', 'Sci-Fi')
(184, 184, 'SMOOCHY CONTROL', 'Sports')
(185, 185, 'MUSCLE BRIGHT', 'Travel')
(185, 185, 'SWEET BROTHERHOOD', 'Travel')

- delete a tabela temporária

In [35]:
db('DROP TABLE max_duration')

Executando query:

### Desafio!

- Gere uma tabela contendo, para cada ator, a seguinte informação:

| first_name | last_name | filmes por categoria |
|--|--|--|
| PENELOPE | GUINESS | Animation: ANACONDA CONFESSIONS; Children: LANGUAGE COWBOY; Classics: COLOR PHILADELPHIA, WESTWARD SEABISCUIT; Comedy: VERTIGO NORTHWEST; Documentary: ACADEMY DINOSAUR; Family: KING EVOLUTION, SPLASH GUMP; Foreign: MULHOLLAND BEAST; Games: BULWORTH COMMANDMENTS, HUMAN GRAFFITI; Horror: ELEPHANT TROJAN, LADY STAGE, RULES HUMAN; Music: WIZARD COLDBLOODED; New: ANGELS LIFE, OKLAHOMA JUMANJI; Sci-Fi: CHEAPER CLYDE; Sports: GLEAMING JAWBREAKER |
| NICK | WAHLBERG | Action: BULL SHAWSHANK; Animation: FIGHT JAWBREAKER; Children: JERSEY SASSY; Classics: DRACULA CRYSTAL, GILBERT PELICAN; Comedy: MALLRATS UNITED, RUSHMORE MERMAID; Documentary: ADAPTATION HOLES; Drama: WARDROBE PHANTOM; Family: APACHE DIVINE, CHISUM BEHAVIOR, INDIAN LOVE, MAGUIRE APACHE; Foreign: BABY HALL, HAPPINESS UNITED; Games: ROOF CHAMPION; Music: LUCKY FLYING; New: DESTINY SATURDAY, FLASH WARS, JEKYLL FROGMEN, MASK PEACH; Sci-Fi: CHAINSAW UPTOWN, GOODFELLAS SALUTE; Travel: LIAISONS SWEET, SMILE EARRING |
| etc | etc | etc |

Dica: use `GROUP_CONCAT` para agrupar todas as strings de uma coluna em uma string só, e `CONCAT` para unir strings particulares.

In [36]:
db('DROP TABLE IF EXISTS ator_categoria_filmes')
db('''
CREATE TEMPORARY TABLE ator_categoria_filmes
    SELECT 
        actor_id, 
        first_name, 
        last_name, 
        CONCAT(
            name,
            ": ",
            GROUP_CONCAT(title ORDER BY title SEPARATOR ", ")
        ) as cat_film
    FROM
        actor
        INNER JOIN film_actor USING (actor_id)
        INNER JOIN film USING (film_id)
        INNER JOIN film_category USING (film_id)
        INNER JOIN category USING (category_id)
    GROUP BY 
        actor_id, category_id
''')

Executando query:
Executando query:

In [39]:
db('SELECT * FROM ator_categoria_filmes LIMIT 10')

Executando query:
(1, 'PENELOPE', 'GUINESS', 'Animation: ANACONDA CONFESSIONS')
(1, 'PENELOPE', 'GUINESS', 'Children: LANGUAGE COWBOY')
(1, 'PENELOPE', 'GUINESS', 'Classics: COLOR PHILADELPHIA, WESTWARD SEABISCUIT')
(1, 'PENELOPE', 'GUINESS', 'Comedy: VERTIGO NORTHWEST')
(1, 'PENELOPE', 'GUINESS', 'Documentary: ACADEMY DINOSAUR')
(1, 'PENELOPE', 'GUINESS', 'Family: KING EVOLUTION, SPLASH GUMP')
(1, 'PENELOPE', 'GUINESS', 'Foreign: MULHOLLAND BEAST')
(1, 'PENELOPE', 'GUINESS', 'Games: BULWORTH COMMANDMENTS, HUMAN GRAFFITI')
(1, 'PENELOPE', 'GUINESS', 'Horror: ELEPHANT TROJAN, LADY STAGE, RULES HUMAN')
(1, 'PENELOPE', 'GUINESS', 'Music: WIZARD COLDBLOODED')

In [38]:
db('''
SELECT
    first_name, 
    last_name, 
    GROUP_CONCAT(cat_film ORDER BY cat_film SEPARATOR "; ")
FROM
    ator_categoria_filmes
GROUP BY 
    actor_id
''')

Executando query:

ProgrammingError: 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sakila.ator_categoria_filmes.first_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

## Variáveis

Podemos montar uma query que retorne um valor só e armazenar este valor em uma variável, para uso posterior em outras queries. Para isso vamos usar o prefixo '@' para indicar variáveis, e o comando `SELECT ... INTO`.

Exemplo: quais são os filmes "caros" da nossa base sakila? Vamos descobrir quais filmes custam mais que um desvio padrão acima da média de preços de locação.

Primeiro vamos calcular a média e o desvio padrão dos preços de aluguel:

In [39]:
db('''
SELECT 
    AVG(rental_rate), 
    STDDEV(rental_rate)
INTO 
    @avg_rate, 
    @stddev_rate 
FROM
    film;
''')

Executando query:

Note que a query não retorna um resultado: o resultado foi armazenado direto nas variáveis `@avg_rate` e `@stddev_rate`. Vamos usar um `SELECT` sem tabelas para ver o resultado:

In [40]:
db('SELECT @avg_rate, @stddev_rate')

Executando query:
(Decimal('2.980000000'), 1.6455698101265719)

Agora podemos selecionar os filmes caros!

In [41]:
db('''
SELECT 
    title, rental_rate
FROM
    film
WHERE
    rental_rate > @avg_rate + @stddev_rate;
''')

Executando query:
('ACE GOLDFINGER', Decimal('4.99'))
('AIRPLANE SIERRA', Decimal('4.99'))
('AIRPORT POLLOCK', Decimal('4.99'))
('ALADDIN CALENDAR', Decimal('4.99'))
('ALI FOREVER', Decimal('4.99'))
('AMELIE HELLFIGHTERS', Decimal('4.99'))
('AMERICAN CIRCUS', Decimal('4.99'))
('ANTHEM LUKE', Decimal('4.99'))
('APACHE DIVINE', Decimal('4.99'))
('APOCALYPSE FLAMINGOS', Decimal('4.99'))
('ATTACKS HATE', Decimal('4.99'))
('ATTRACTION NEWTON', Decimal('4.99'))
('AUTUMN CROW', Decimal('4.99'))
('BABY HALL', Decimal('4.99'))
('BACKLASH UNDEFEATED', Decimal('4.99'))
('BEAST HUNCHBACK', Decimal('4.99'))
('BEAUTY GREASE', Decimal('4.99'))
('BEHAVIOR RUNAWAY', Decimal('4.99'))
('BETRAYED REAR', Decimal('4.99'))
('BIKINI BORROWERS', Decimal('4.99'))
('BILKO ANONYMOUS', Decimal('4.99'))
('BIRCH ANTITRUST', Decimal('4.99'))
('BIRD INDEPENDENCE', Decimal('4.99'))
('BIRDS PERDITION', Decimal('4.99'))
('BLINDNESS GUN', Decimal('4.99'))
('BOILED DARES', Decimal('4.99'))
('BOOGIE AMELIE', Decimal('4.99'))
('BORN SPINAL', Decimal('4.99'))
('BOWFINGER GABLES', Decimal('4.99'))
('BRANNIGAN SUNRISE', Decimal('4.99'))
('BREAKFAST GOLDFINGER', Decimal('4.99'))
('BRIGHT ENCOUNTERS', Decimal('4.99'))
('BROOKLYN DESERT', Decimal('4.99'))
('BUBBLE GROSSE', Decimal('4.99'))
('BUCKET BROTHERHOOD', Decimal('4.99'))
('CALENDAR GUNFIGHT', Decimal('4.99'))
('CALIFORNIA BIRDS', Decimal('4.99'))
('CANDLES GRAPES', Decimal('4.99'))
('CARIBBEAN LIBERTY', Decimal('4.99'))
('CASABLANCA SUPER', Decimal('4.99'))
('CASPER DRAGONFLY', Decimal('4.99'))
('CASUALTIES ENCINO', Decimal('4.99'))
('CAT CONEHEADS', Decimal('4.99'))
('CENTER DINOSAUR', Decimal('4.99'))
('CHAMBER ITALIAN', Decimal('4.99'))
('CHAMPION FLATLINERS', Decimal('4.99'))
('CHASING FIGHT', Decimal('4.99'))
('CHICAGO NORTH', Decimal('4.99'))
('CHINATOWN GLADIATOR', Decimal('4.99'))
('CHISUM BEHAVIOR', Decimal('4.99'))
('CINCINATTI WHISPERER', Decimal('4.99'))
('CLERKS ANGELS', Decimal('4.99'))
('CLOSER BANG', Decimal('4.99'))
('CLUE GRAIL', Decimal('4.99'))
('COLDBLOODED DARLING', Decimal('4.99'))
('COMA HEAD', Decimal('4.99'))
('COMMAND DARLING', Decimal('4.99'))
('COMMANDMENTS EXPRESS', Decimal('4.99'))
('CONEHEADS SMOOCHY', Decimal('4.99'))
('CONFESSIONS MAGUIRE', Decimal('4.99'))
('CONFIDENTIAL INTERVIEW', Decimal('4.99'))
('CONNECTICUT TRAMP', Decimal('4.99'))
('CONQUERER NUTS', Decimal('4.99'))
('CONTROL ANTHEM', Decimal('4.99'))
('CONVERSATION DOWNHILL', Decimal('4.99'))
('CREEPERS KANE', Decimal('4.99'))
('CROSSING DIVORCE', Decimal('4.99'))
('CROWDS TELEMARK', Decimal('4.99'))
('DADDY PITTSBURGH', Decimal('4.99'))
('DAISY MENAGERIE', Decimal('4.99'))
('DANGEROUS UPTOWN', Decimal('4.99'))
('DARKO DORADO', Decimal('4.99'))
('DARLING BREAKING', Decimal('4.99'))
('DARN FORRESTER', Decimal('4.99'))
('DAUGHTER MADIGAN', Decimal('4.99'))
('DAWN POND', Decimal('4.99'))
('DAY UNFAITHFUL', Decimal('4.99'))
('DAZED PUNK', Decimal('4.99'))
('DEEP CRUSADE', Decimal('4.99'))
('DESERT POSEIDON', Decimal('4.99'))
('DESPERATE TRAINSPOTTING', Decimal('4.99'))
('DESTINY SATURDAY', Decimal('4.99'))
('DETAILS PACKER', Decimal('4.99'))
('DEVIL DESIRE', Decimal('4.99'))
('DOGMA FAMILY', Decimal('4.99'))
('DOORS PRESIDENT', Decimal('4.99'))
('DORADO NOTTING', Decimal('4.99'))
('DOUBTFIRE LABYRINTH', Decimal('4.99'))
('DOZEN LION', Decimal('4.99'))
('DRAGONFLY STRANGERS', Decimal('4.99'))
('DRIFTER COMMANDMENTS', Decimal('4.99'))
('DRIVING POLISH', Decimal('4.99'))
('DROP WATERFRONT', Decimal('4.99'))
('DUDE BLINDNESS', Decimal('4.99'))
('DURHAM PANKY', Decimal('4.99'))
('DYING MAKER', Decimal('4.99'))
('EAGLES PANKY', Decimal('4.99'))
('EARLY HOME', Decimal('4.99'))
('EASY GLADIATOR', Decimal('4.99'))
('EDGE KISSING', Decimal('4.99'))
('ELEMENT FREDDY', Decimal('4.99'))
('ELEPHANT TROJAN', Decimal('4.99'))
('ELF MURDER', Decimal('4.99'))
('ELIZABETH SHANE', Decimal('4.99'))
('ENEMY ODDS', Decimal('4.99'))
('EVE RESURRECTION', Decimal('4.99'))
('EXPECATIONS NATURAL', Decimal('4.99'))
('FALCON VOLUME', Decimal('4.99'))
('FELLOWSHIP AUTUMN', Decimal('4.99'))
('FEVER EMPIRE', Decimal('4.99'))
('FIDDLER LOST', Decimal('4.99'))
('FIDELITY DEVIL', Decimal('4.99'))
('FIRE WOLVES', Decimal('4.99'))
('FLAMINGOS CONNECTICUT', Decimal('4.99'))
('FLASH WARS', Decimal('4.99'))
('FLIGHT LIES', Decimal('4.99'))
('FLINTSTONES HAPPINESS', Decimal('4.99'))
('FOOL MOCKINGBIRD', Decimal('4.99'))
('FORRESTER COMANCHEROS', Decimal('4.99'))
('FREDDY STORM', Decimal('4.99'))
('FRENCH HOLIDAY', Decimal('4.99'))
('FRISCO FORREST', Decimal('4.99'))
('FRONTIER CABIN', Decimal('4.99'))
('FUGITIVE MAGUIRE', Decimal('4.99'))
('GALAXY SWEETHEARTS', Decimal('4.99'))
('GAMES BOWFINGER', Decimal('4.99'))
('GARDEN ISLAND', Decimal('4.99'))
('GHOST GROUNDHOG', Decimal('4.99'))
('GLADIATOR WESTWARD', Decimal('4.99'))
('GOLD RIVER', Decimal('4.99'))
('GOODFELLAS SALUTE', Decimal('4.99'))
('GOSFORD DONNIE', Decimal('4.99'))
('GRACELAND DYNAMITE', Decimal('4.99'))
('GRINCH MASSAGE', Decimal('4.99'))
('GROSSE WONDERFUL', Decimal('4.99'))
('GROUNDHOG UNCUT', Decimal('4.99'))
('GUMP DATE', Decimal('4.99'))
('GUYS FALCON', Decimal('4.99'))
('HALL CASSIDY', Decimal('4.99'))
('HANGING DEEP', Decimal('4.99'))
('HANOVER GALAXY', Decimal('4.99'))
('HARRY IDAHO', Decimal('4.99'))
('HAUNTED ANTITRUST', Decimal('4.99'))
('HEAD STRANGER', Decimal('4.99'))
('HEARTBREAKERS BRIGHT', Decimal('4.99'))
('HEAVENLY GUN', Decimal('4.99'))
('HEAVYWEIGHTS BEAST', Decimal('4.99'))
('HOLES BRANNIGAN', Decimal('4.99'))
('HOLIDAY GAMES', Decimal('4.99'))
('HOLLOW JEOPARDY', Decimal('4.99'))
('HOME PITY', Decimal('4.99'))
('HOTEL HAPPINESS', Decimal('4.99'))
('HUNCHBACK IMPOSSIBLE', Decimal('4.99'))
('HUSTLER PARTY', Decimal('4.99'))
('HYSTERICAL GRAIL', Decimal('4.99'))
('IGBY MAKER', Decimal('4.99'))
('IMPOSSIBLE PREJUDICE', Decimal('4.99'))
('INCH JET', Decimal('4.99'))
('INFORMER DOUBLE', Decimal('4.99'))
('INNOCENT USUAL', Decimal('4.99'))
('INTERVIEW LIAISONS', Decimal('4.99'))
('INTOLERABLE INTENTIONS', Decimal('4.99'))
('IRON MOON', Decimal('4.99'))
('ISHTAR ROCKETEER', Decimal('4.99'))
('ITALIAN AFRICAN', Decimal('4.99'))
('JERSEY SASSY', Decimal('4.99'))
('JET NEIGHBORS', Decimal('4.99'))
('JINGLE SAGEBRUSH', Decimal('4.99'))
('KING EVOLUTION', Decimal('4.99'))
('KISS GLORY', Decimal('4.99'))
('KISSING DOLLS', Decimal('4.99'))
('LADY STAGE', Decimal('4.99'))
('LAMBS CINCINATTI', Decimal('4.99'))
('LAWLESS VISION', Decimal('4.99'))
('LEAGUE HELLFIGHTERS', Decimal('4.99'))
('LEGALLY SECRETARY', Decimal('4.99'))
('LIAISONS SWEET', Decimal('4.99'))
('LIES TREATMENT', Decimal('4.99'))
('LOLA AGENT', Decimal('4.99'))
('LOSER HUSTLER', Decimal('4.99'))
('MADIGAN DORADO', Decimal('4.99'))
('MAIDEN HOME', Decimal('4.99'))
('MALTESE HOPE', Decimal('4.99'))
('MASSACRE USUAL', Decimal('4.99'))
('MATRIX SNOWMAN', Decimal('4.99'))
('MEMENTO ZOOLANDER', Decimal('4.99'))
('MERMAID INSECTS', Decimal('4.99'))
('MIDSUMMER GROUNDHOG', Decimal('4.99'))
('MILLION ACE', Decimal('4.99'))
('MINDS TRUMAN', Decimal('4.99'))
('MINE TITANS', Decimal('4.99'))
('MISSION ZOOLANDER', Decimal('4.99'))
('MOD SECRETARY', Decimal('4.99'))
('MODEL FISH', Decimal('4.99'))
('MONSOON CAUSE', Decimal('4.99'))
('MOONSHINE CABIN', Decimal('4.99'))
('MOONWALKER FOOL', Decimal('4.99'))
('MOVIE SHAKESPEARE', Decimal('4.99'))
('MUPPET MILE', Decimal('4.99'))
('MUSKETEERS WAIT', Decimal('4.99'))
('NAME DETECTIVE', Decimal('4.99'))
('NIGHTMARE CHILL', Decimal('4.99'))
('NORTH TEQUILA', Decimal('4.99'))
('NUTS TIES', Decimal('4.99'))
('OCTOBER SUBMARINE', Decimal('4.99'))
('OPEN AFRICAN', Decimal('4.99'))
('OPPOSITE NECKLACE', Decimal('4.99'))
('OPUS ICE', Decimal('4.99'))
('OUTLAW HANKY', Decimal('4.99'))
('PANIC CLUB', Decimal('4.99'))
('PANKY SUBMARINE', Decimal('4.99'))
('PANTHER REDS', Decimal('4.99'))
('PARK CITIZEN', Decimal('4.99'))
('PAST SUICIDES', Decimal('4.99'))
('PATHS CONTROL', Decimal('4.99'))
('PAYCHECK WAIT', Decimal('4.99'))
('PEAK FOREVER', Decimal('4.99'))
('PELICAN COMFORTS', Decimal('4.99'))
('PERDITION FARGO', Decimal('4.99'))
('PHILADELPHIA WIFE', Decimal('4.99'))
('PINOCCHIO SIMON', Decimal('4.99'))
('PITTSBURGH HUNCHBACK', Decimal('4.99'))
('PITY BOUND', Decimal('4.99'))
('PLATOON INSTINCT', Decimal('4.99'))
('PLUTO OLEANDER', Decimal('4.99'))
('POSEIDON FOREVER', Decimal('4.99'))
('PREJUDICE OLEANDER', Decimal('4.99'))
('PRESIDENT BANG', Decimal('4.99'))
('PRIVATE DROP', Decimal('4.99'))
('PUNK DIVORCE', Decimal('4.99'))
('QUEEN LUKE', Decimal('4.99'))
('QUILLS BULL', Decimal('4.99'))
('RAGE GAMES', Decimal('4.99'))
('RAGING AIRPLANE', Decimal('4.99'))
('RAINBOW SHOCK', Decimal('4.99'))
('RANGE MOONWALKER', Decimal('4.99'))
('RECORDS ZORRO', Decimal('4.99'))
('REDS POCUS', Decimal('4.99'))
('REQUIEM TYCOON', Decimal('4.99'))
('RIGHT CRANES', Decimal('4.99'))
('ROAD ROXANNE', Decimal('4.99'))
('ROCKY WAR', Decimal('4.99'))
('ROSES TREASURE', Decimal('4.99'))
('RULES HUMAN', Decimal('4.99'))
('SABRINA MIDNIGHT', Decimal('4.99'))
('SATISFACTION CONFIDENTIAL', Decimal('4.99'))
('SATURDAY LAMBS', Decimal('4.99'))
('SATURN NAME', Decimal('4.99'))
('SCALAWAG DUCK', Decimal('4.99'))
('SCARFACE BANG', Decimal('4.99'))
('SCHOOL JACKET', Decimal('4.99'))
('SCORPION APOLLO', Decimal('4.99'))
('SEATTLE EXPECATIONS', Decimal('4.99'))
('SECRET GROUNDHOG', Decimal('4.99'))
('SECRETARY ROUGE', Decimal('4.99'))
('SECRETS PARADISE', Decimal('4.99'))
('SENSE GREEK', Decimal('4.99'))
('SENSIBILITY REAR', Decimal('4.99'))
('SEVEN SWARM', Decimal('4.99'))
('SHAWSHANK BUBBLE', Decimal('4.99'))
('SHOW LORD', Decimal('4.99'))
('SILVERADO GOLDFINGER', Decimal('4.99'))
('SISTER FREDDY', Decimal('4.99'))
('SLACKER LIAISONS', Decimal('4.99'))
('SLEEPING SUSPECTS', Decimal('4.99'))
('SLEEPLESS MONSOON', Decimal('4.99'))
('SNATCH SLIPPER', Decimal('4.99'))
('SOLDIERS EVOLUTION', Decimal('4.99'))
('SOMETHING DUCK', Decimal('4.99'))
('SPARTACUS CHEAPER', Decimal('4.99'))
('SPEED SUIT', Decimal('4.99'))
('SPICE SORORITY', Decimal('4.99'))
('STAGECOACH ARMAGEDDON', Decimal('4.99'))
('STEEL SANTA', Decimal('4.99'))
('STEERS ARMAGEDDON', Decimal('4.99'))
('STEPMOM DREAM', Decimal('4.99'))
('STING PERSONAL', Decimal('4.99'))
('STRANGER STRANGERS', Decimal('4.99'))
('STRANGERS GRAFFITI', Decimal('4.99'))
('STREETCAR INTENTIONS', Decimal('4.99'))
('SUBMARINE BED', Decimal('4.99'))
('SUGAR WONKA', Decimal('4.99'))
('SUICIDES SILENCE', Decimal('4.99'))
('SUIT WALLS', Decimal('4.99'))
('SUNRISE LEAGUE', Decimal('4.99'))
('SUPER WYOMING', Decimal('4.99'))
('SWEDEN SHINING', Decimal('4.99'))
('TEEN APOLLO', Decimal('4.99'))
('TELEGRAPH VOYAGE', Decimal('4.99'))
('TEMPLE ATTRACTION', Decimal('4.99'))
('TEQUILA PAST', Decimal('4.99'))
('TERMINATOR CLUB', Decimal('4.99'))
('THIEF PELICAN', Decimal('4.99'))
('THIN SAGEBRUSH', Decimal('4.99'))
('TIES HUNGER', Decimal('4.99'))
('TITANIC BOONDOCK', Decimal('4.99'))
('TITANS JERK', Decimal('4.99'))
('TORQUE BOUND', Decimal('4.99'))
('TOURIST PELICAN', Decimal('4.99'))
('TRADING PINOCCHIO', Decimal('4.99'))
('TRAFFIC HOBBIT', Decimal('4.99'))
('TRAIN BUNCH', Decimal('4.99'))
('TRAINSPOTTING STRANGERS', Decimal('4.99'))
('TRAP GUYS', Decimal('4.99'))
('TRIP NEWTON', Decimal('4.99'))
('TRUMAN CRAZY', Decimal('4.99'))
('TWISTED PIRATES', Decimal('4.99'))
('TYCOON GATHERING', Decimal('4.99'))
('UNDEFEATED DALMATIONS', Decimal('4.99'))
('USUAL UNTOUCHABLES', Decimal('4.99'))
('VAMPIRE WHALE', Decimal('4.99'))
('VANILLA DAY', Decimal('4.99'))
('VELVET TERMINATOR', Decimal('4.99'))
('VIDEOTAPE ARSENIC', Decimal('4.99'))
('VILLAIN DESPERATE', Decimal('4.99'))
('VIRGIN DAISY', Decimal('4.99'))
('VIRTUAL SPOILERS', Decimal('4.99'))
('VOLUME HOUSE', Decimal('4.99'))
('WAKE JAWS', Decimal('4.99'))
('WALLS ARTIST', Decimal('4.99'))
('WANDA CHAMBER', Decimal('4.99'))
('WAR NOTTING', Decimal('4.99'))
('WASH HEAVENLY', Decimal('4.99'))
('WATERFRONT DELIVERANCE', Decimal('4.99'))
('WEREWOLF LOLA', Decimal('4.99'))
('WEST LION', Decimal('4.99'))
('WHALE BIKINI', Decimal('4.99'))
('WHISPERER GIANT', Decimal('4.99'))
('WIFE TURN', Decimal('4.99'))
('WITCHES PANIC', Decimal('4.99'))
('WIZARD COLDBLOODED', Decimal('4.99'))
('WONDERLAND CHRISTMAS', Decimal('4.99'))
('WORKING MICROCOSMOS', Decimal('4.99'))
('WYOMING STORM', Decimal('4.99'))
('YENTL IDAHO', Decimal('4.99'))
('ZORRO ARK', Decimal('4.99'))

### Vamos praticar

Use variáveis temporárias para encontrar o ator que mais participou de filmes.

## Operador `IN`

Suponha que desejamos listar todos os filmes dos 3 atores mais populares. Podemos começar listando os 3 atores mais populares:

In [42]:
db('''
SELECT 
    actor_id, first_name, last_name, COUNT(film_id) AS num_films
FROM
    actor
    INNER JOIN film_actor USING (actor_id)
GROUP BY 
    actor_id
ORDER BY 
    num_films DESC
LIMIT 3
''')

Executando query:
(107, 'GINA', 'DEGENERES', 42)
(102, 'WALTER', 'TORN', 41)
(198, 'MARY', 'KEITEL', 40)

Vamos criar uma tabela temporária para guardar a informação de `actor_id` desses atores:

In [43]:
db('DROP TABLE IF EXISTS temp_pop_actors')
db('''
CREATE TEMPORARY TABLE temp_pop_actors
    SELECT first_name, last_name, actor_id FROM
        actor
        INNER JOIN film_actor USING (actor_id)
    GROUP BY 
        actor_id
    ORDER BY 
        COUNT(film_id) DESC
    LIMIT 3
''')
db('''
SELECT * from temp_pop_actors
''')

Executando query:
Executando query:
Executando query:
('GINA', 'DEGENERES', 107)
('WALTER', 'TORN', 102)
('MARY', 'KEITEL', 198)

Por fim, vamos usar essa informação para listar os filmes dos atores populares:

In [44]:
db('''
SELECT DISTINCT
    title
FROM
    film
    INNER JOIN film_actor USING (film_id)
WHERE
    actor_id IN (SELECT actor_id FROM temp_pop_actors);
''')

Executando query:
('BED HIGHBALL',)
('CALENDAR GUNFIGHT',)
('CHAMBER ITALIAN',)
('CHAPLIN LICENSE',)
('CHARIOTS CONSPIRACY',)
('CLUELESS BUCKET',)
('COLDBLOODED DARLING',)
('CONEHEADS SMOOCHY',)
('DARKNESS WAR',)
('DEER VIRGINIAN',)
('DOGMA FAMILY',)
('ELEPHANT TROJAN',)
('EXCITEMENT EVE',)
('FRISCO FORREST',)
('GANDHI KWAI',)
('GOODFELLAS SALUTE',)
('GUNFIGHT MOON',)
('HALL CASSIDY',)
('HEARTBREAKERS BRIGHT',)
('HOOK CHARIOTS',)
('HYDE DOCTOR',)
('IMPACT ALADDIN',)
('INDIAN LOVE',)
('INTRIGUE WORST',)
('LICENSE WEEKEND',)
('LOUISIANA HARRY',)
('MAGNIFICENT CHITTY',)
('METAL ARMAGEDDON',)
('MIDNIGHT WESTWARD',)
('MOVIE SHAKESPEARE',)
('MUMMY CREATURES',)
('OPEN AFRICAN',)
('SEARCHERS WAIT',)
('SEVEN SWARM',)
('SIERRA DIVIDE',)
('SPIRITED CASUALTIES',)
('STORM HAPPINESS',)
('SUGAR WONKA',)
('TELEGRAPH VOYAGE',)
('TRAINSPOTTING STRANGERS',)
('WIFE TURN',)
('WINDOW SIDE',)
('AMELIE HELLFIGHTERS',)
('ARABIA DOGMA',)
('BANG KWAI',)
('CASABLANCA SUPER',)
('CASPER DRAGONFLY',)
('CROW GREASE',)
('CURTAIN VIDEOTAPE',)
('DANCES NONE',)
('EARLY HOME',)
('FLYING HOOK',)
('FORREST SONS',)
('FREDDY STORM',)
('GASLIGHT CRUSADE',)
('HOBBIT ALIEN',)
('HOOSIERS BIRDCAGE',)
('HYSTERICAL GRAIL',)
('JERSEY SASSY',)
('LAMBS CINCINATTI',)
('LESSON CLEOPATRA',)
('LIES TREATMENT',)
('LOCK REAR',)
('LONELY ELEPHANT',)
('MADISON TRAP',)
('MOTIONS DETAILS',)
('MULHOLLAND BEAST',)
('NIGHTMARE CHILL',)
('NOVOCAINE FLIGHT',)
('RAIDERS ANTITRUST',)
('REUNION WITCHES',)
('ROOTS REMEMBER',)
('SKY MIRACLE',)
('SLUMS DUCK',)
('SPIKING ELEMENT',)
('STAGE WORLD',)
('STEPMOM DREAM',)
('STRANGELOVE DESIRE',)
('WARDROBE PHANTOM',)
('WITCHES PANIC',)
('WIZARD COLDBLOODED',)
('ACADEMY DINOSAUR',)
('BUTTERFLY CHOCOLAT',)
('CASSIDY WYOMING',)
('CRAFT OUTFIELD',)
('DUMBO LUST',)
('DWARFS ALTER',)
('FANTASY TROOPERS',)
('FEUD FROGMEN',)
('FICTION CHRISTMAS',)
('GAMES BOWFINGER',)
('GREEDY ROOTS',)
('HANDICAP BOONDOCK',)
('HAUNTING PIANIST',)
('IDOLS SNATCHERS',)
('INTENTIONS EMPIRE',)
('JEOPARDY ENCINO',)
('KING EVOLUTION',)
('LOVELY JINGLE',)
('LUKE MUMMY',)
('MADNESS ATTACKS',)
('MALLRATS UNITED',)
('MEMENTO ZOOLANDER',)
('MERMAID INSECTS',)
('MODEL FISH',)
('MOONWALKER FOOL',)
('NORTHWEST POLISH',)
('ROSES TREASURE',)
('SAINTS BRIDE',)
('SLEEPY JAPANESE',)
('SOLDIERS EVOLUTION',)
('STEEL SANTA',)
('SUBMARINE BED',)
('SWEDEN SHINING',)
('THEORY MERMAID',)
('TITANIC BOONDOCK',)
('UNFORGIVEN ZOOLANDER',)
('WAGON JAWS',)
('YOUTH KICK',)

Note o uso de *subqueries*!

Não se esqueça de limpar tudo no final!

In [45]:
db('DROP TABLE temp_pop_actors')

Executando query:

### Vamos praticar

Liste os atores que participaram dos 3 filmes mais rentáveis (aqueles que mais geraram receita para a locadora).

## Subqueries

Os tópicos discutidos acima poderiam ser resolvidos, em grande parte, com subqueries. As subqueries são queries `SELECT` criadas dentro de outras queries. 

Poderíamos ter usado subqueries nos mesmos lugares onde usamos tabelas temporárias, nos tópicos acima. Quando a subquery pode ser transformada em uma tabela temporária independente, separada da query exterior, dizemos que a subquery é **não-correlacionada** com a query exterior.

Usar subqueries não-correlacionadas é um tópico controverso: podemos sempre usar uma tabela temporária ou, ás vezes, pensar em um `JOIN` simples. Aliás, muitas vezes o otimizador de queries do banco de dados transformará a subquery em `JOIN`, se isso for vantajoso em termos de desempenho.

Uma subquery que depende da query externa (e portanto não pode ser separada em uma tabela temporária independente) é chamada de **subquery correlacionada**. Nestes casos podemos ter que executar a subquery para cada linha da query exterior!

### Vamos praticar

Vamos refazer a atividade dos filmes de atores populares, usando subqueries. 

Temos um problema: o MySQL não suporta ``LIMIT`` em subqueries com o operador ``IN``. Vamos investigar isso mais de perto. 

Em primeiro lugar faça uma tradução direta da implementação da atividade anterior trocando tabela temporária por subquery.

In [46]:
try:
    db('''
    SELECT 
        actor_id, first_name, last_name
    FROM
        actor
        INNER JOIN film_actor USING (actor_id)
    WHERE
        film_actor.film_id IN (
            SELECT 
                film_id
            FROM
                film
                INNER JOIN inventory USING (film_id)
                INNER JOIN rental USING (inventory_id)
                INNER JOIN payment USING (rental_id)
            WHERE
                payment_date IS NOT NULL
            GROUP BY film_id
            ORDER BY SUM(amount)
            LIMIT 3) tab_aux
    ORDER BY actor_id
    ''')
except mysql.connector.ProgrammingError as e:
    print(f'ProgrammingError: {e}')

Executando query:
ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tab_aux
    ORDER BY actor_id' at line 19

Ok, apareceu o problema. Mas considere que o problema original não precisava de IN desde o começo! Construa essa solução.

# `UNION`

Quando duas tabelas tem **EXATAMENTE** as mesmas colunas, podemos concatená-las e formar uma grande tabela unificada usando o operador `UNION`. Por exemplo: suponha que desejamos montar uma lista dos nomes e sobrenomes de todos os clientes E de todos os funcionários. Eis uma solução possível:

In [47]:
db('DROP TABLE IF EXISTS nomes_clientes')
db('''
CREATE TEMPORARY TABLE nomes_clientes 
    SELECT first_name, last_name FROM customer
''')

Executando query:
Executando query:

In [48]:
db('DESCRIBE nomes_clientes')
db('SELECT * FROM nomes_clientes LIMIT 5')

Executando query:
('first_name', 'varchar(45)', 'NO', '', None, 'NULL')
('last_name', 'varchar(45)', 'NO', '', None, 'NULL')
Executando query:
('MARY', 'SMITH')
('PATRICIA', 'JOHNSON')
('LINDA', 'WILLIAMS')
('BARBARA', 'JONES')
('ELIZABETH', 'BROWN')

In [49]:
db('DROP TABLE IF EXISTS nomes_staff')
db('''
CREATE TEMPORARY TABLE nomes_staff 
    SELECT first_name, last_name FROM staff
''')

Executando query:
Executando query:

In [50]:
db('DESCRIBE nomes_staff')
db('SELECT * FROM nomes_staff LIMIT 5')

Executando query:
('first_name', 'varchar(45)', 'NO', '', None, 'NULL')
('last_name', 'varchar(45)', 'NO', '', None, 'NULL')
Executando query:
('Mike', 'Hillyer')
('Jon', 'Stephens')

In [51]:
db('DROP TABLE IF EXISTS nomes_all')
db('''CREATE TEMPORARY TABLE nomes_all 
    (SELECT * FROM nomes_staff) UNION (SELECT * FROM nomes_clientes)
''')

Executando query:
Executando query:

In [52]:
db('DESCRIBE nomes_all')
db('SELECT * FROM nomes_all LIMIT 5')

Executando query:
('first_name', 'varchar(45)', 'NO', '', '', 'NULL')
('last_name', 'varchar(45)', 'NO', '', '', 'NULL')
Executando query:
('Mike', 'Hillyer')
('Jon', 'Stephens')
('MARY', 'SMITH')
('PATRICIA', 'JOHNSON')
('LINDA', 'WILLIAMS')

In [53]:
db('DROP TABLE IF EXISTS nomes_clientes')
db('DROP TABLE IF EXISTS nomes_staff')
db('DROP TABLE IF EXISTS nomes_all')

Executando query:
Executando query:
Executando query:

**Vamos praticar:** refaça o exemplo acima mas use *subqueries* ao invés de *temp tables*.

## Desafios!

Faça uma lista de filmes que tenham mais de dois atores cujo nome inicia com a mesma letra do título do filme!

In [54]:
db('''
SELECT
    title
FROM
    film
    INNER JOIN film_actor USING (film_id)
    INNER JOIN actor USING (actor_id)
WHERE
    LEFT(title, 1) = LEFT(first_name, 1)
GROUP BY
    film_id
HAVING
    COUNT(actor_id) > 2
''')

Executando query:
('CROW GREASE',)
('JEDI BENEATH',)
('SUBMARINE BED',)

Semana do "DAN HARRIS": liste os clientes que nunca assistiram um filme do ator "DAN HARRIS" ou que já assistiram mas onde a ultima vez em que assistiram um filme dele foi antes de '2005-06-01'

In [72]:
db('DROP TABLE IF EXISTS films_dan')
db('''
CREATE TEMPORARY TABLE films_dan
    SELECT DISTINCT
        film_id
    FROM
        film_actor 
        INNER JOIN actor USING (actor_id)
    WHERE
        first_name = "DAN" AND last_name = "HARRIS"
    ORDER BY
        film_id
''')
db('SELECT * FROM films_dan')

Executando query:
Executando query:
Executando query:
(63,)
(87,)
(226,)
(236,)
(298,)
(307,)
(354,)
(383,)
(417,)
(421,)
(457,)
(462,)
(474,)
(521,)
(593,)
(728,)
(750,)
(769,)
(781,)
(795,)
(844,)
(851,)
(862,)
(868,)
(892,)
(893,)
(936,)
(965,)

In [77]:
db('''
SELECT
    COUNT(DISTINCT customer_id)
FROM
    customer
    LEFT OUTER JOIN rental USING (customer_id)
    LEFT OUTER JOIN inventory USING (inventory_id)
    LEFT OUTER JOIN films_dan USING (film_id)
WHERE
    films_dan.film_id IS NULL
''')

Executando query:
(599,)

## Conclusão

Façamos uma pausa para apreciar quão longe estamos: já conseguimos criar nossas tabelas, inserir informação, removê-la, atualizá-la, e consultar nossa base de maneiras bem sofisticadas! Vimos desde `SELECT` simples até buscas mais complexas envolvendo várias etapas de processamento para obter o dado desejado.

Por hoje é só, feche sua conexão e bom descanso!

In [ ]:
connection.close()